const modal=document.getElementById('modal');const startBtn=document.getElementById('startBtn');const demoBtn=document.getElementById('demoBtn');const closeBtn=document.getElementById('closeBtn');const continueBtn=document.getElementById('continueBtn');const choices=[...document.querySelectorAll('.career-choice')];const clubGrid=document.getElementById('clubGrid');const careerStep=document.getElementById('careerStep');const createStep=document.getElementById('createStep');const createClubBtn=document.getElementById('createClubBtn');const saveClubBtn=document.getElementById('saveClubBtn');const dashboard=document.getElementById('dashboard');const hero=document.querySelector('.hero');const backToStart=document.getElementById('backToStart');
const clubs=[{name:'Anadolu Yıldızı SK',city:'Bursa',code:'AYS',style:'Balanced'},{name:'Marmara Kartalları',city:'İstanbul',code:'MRK',style:'Attacking'},{name:'Ege Ateşi FK',city:'İzmir',code:'EAF',style:'Technical'},{name:'Trakya Birlik 1926',city:'Edirne',code:'TB26',style:'Defensive'}];
let selectedClub=null;let selectedStyle='Tactical Genius';
function openModal(){modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
function renderClubs(){clubGrid.innerHTML=clubs.map((club,i)=>`<button class="club-choice" data-index="${i}"><b>${club.code}</b><strong>${club.name}</strong><span>${club.city} · ${club.style}</span></button>`).join('');document.querySelectorAll('.club-choice').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.club-choice').forEach(c=>c.classList.remove('selected'));btn.classList.add('selected');selectedClub=clubs[Number(btn.dataset.index)]}))}
function beginCareer(club){const city=club.city;document.getElementById('dashClub').textContent=club.name;document.getElementById('dashCity').textContent=city;document.getElementById('dashStyle').textContent=selectedStyle;document.getElementById('welcomeTitle').textContent=`Congratulations, ${club.name} Manager!`;document.getElementById('welcomeSub').textContent=`${city} · Your 2026/27 journey starts now.`;modal.classList.remove('open');hero.hidden=true;dashboard.hidden=false;document.body.style.overflow='auto';window.scrollTo({top:0,behavior:'smooth'});localStorage.setItem('nexoraCareer',JSON.stringify({club,style:selectedStyle}))}
startBtn.addEventListener('click',()=>{renderClubs();openModal()});demoBtn.addEventListener('click',()=>{renderClubs();openModal()});closeBtn.addEventListener('click',closeModal);choices.forEach(choice=>choice.addEventListener('click',()=>{choices.forEach(c=>c.classList.remove('selected'));choice.classList.add('selected');selectedStyle=choice.dataset.style||choice.querySelector('strong').textContent}));
continueBtn.addEventListener('click',()=>{if(!selectedClub){selectedClub=clubs[0];document.querySelector('.club-choice').classList.add('selected')}beginCareer(selectedClub)});
createClubBtn.addEventListener('click',()=>{careerStep.hidden=true;createStep.hidden=false});saveClubBtn.addEventListener('click',()=>{const name=document.getElementById('clubName').value.trim();const city=document.getElementById('clubCity').value.trim();if(!name||!city){alert('Kulüp adı ve şehir girin.');return}selectedClub={name,city,code:name.slice(0,3).toUpperCase(),style:'Custom'};createStep.hidden=true;careerStep.hidden=false;beginCareer(selectedClub)});
backToStart.addEventListener('click',()=>{dashboard.hidden=true;hero.hidden=false;selectedClub=null;selectedStyle='Tactical Genius';window.scrollTo({top:0,behavior:'smooth'})});modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
