(()=>{
const K='nexoraCareer',read=()=>{try{return JSON.parse(localStorage.getItem(K)||'null')}catch{return null}},save=s=>{localStorage.setItem(K,JSON.stringify(s));localStorage.setItem('nexoraGameState',JSON.stringify(s.gameState))};
const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
function ensure(s){const g=s.gameState;g.careerHistory??={appointments:[],seasons:[],trophies:[],awards:[],matches:0,wins:0,draws:0,losses:0};g.careerHistory.seasons??=[];g.careerHistory.trophies??=[];g.careerHistory.awards??=[];g.europeCoefficients??={tr:14.2,gb:18.6,de:17.7,es:18.4,it:17.9,fr:14.1};return g.careerHistory}
function country(s){return s.gameState.country||window.NEXORA_LEAGUE?.key?.(s)||'tr'}
function recordMatch(s,e){if(e?.type!=='fulltime')return;const g=s.gameState;const h=Number(e.homeGoals||0),a=Number(e.awayGoals||0);g.careerHistory??=ensure(s);const c=g.careerHistory;c.matches=(c.matches||0)+1;if(h>a)c.wins=(c.wins||0)+1;else if(h===a)c.draws=(c.draws||0)+1;else c.losses=(c.losses||0)+1}
function europeanPoints(s,e){if(e?.type!=='fulltime'||s.gameState.nextCompetition!=='europe')return;const k=country(s),h=Number(e.homeGoals||0),a=Number(e.awayGoals||0);s.gameState.europeSeasonPoints??={};s.gameState.europeSeasonPoints[k]??=0;let p=h===a?1:h>a?2:0;if(e.detail?.penaltyWin)p+=1;s.gameState.europeSeasonPoints[k]+=p;s.gameState.europeCoefficients??={tr:14.2,gb:18.6,de:17.7,es:18.4,it:17.9,fr:14.1};}
function awards(s){const g=s.gameState,squad=g.squad||[],hist=g.matchHistory||[];const scorer=squad.map(p=>({...p,goals:Number(p.goals||0)})).sort((a,b)=>b.goals-a.goals||Number(b.rating||0)-Number(a.rating||0))[0];const player=squad.slice().sort((a,b)=>Number(b.rating||0)-Number(a.rating||0))[0];const youth=squad.filter(p=>Number(p.age||99)<=21).sort((a,b)=>Number(b.potential||0)-Number(a.potential||0)||Number(b.rating||0)-Number(a.rating||0))[0];const managerScore=(g.boardConfidence||0)*.55+(g.reputation||0)*.45;const manager={name:g.managerName||'Manager',score:Math.round(managerScore)};const season=g.season;const out={season,goldenBoot:scorer?{name:scorer.name,goals:scorer.goals}:null,playerOfYear:player?{name:player.name,rating:player.rating}:null,managerOfYear:manager,bestYoung:youth?{name:youth.name,rating:youth.rating,potential:youth.potential}:null};g.seasonAwards=out;const c=ensure(s);c.awards.unshift(out);c.awards=c.awards.slice(0,20);g.media??={news:[]};g.media.news.unshift({date:g.date,tag:'AWARDS',market:'GLOBAL',title:'SEASON AWARDS ANNOUNCED',detail:`Golden Boot: ${out.goldenBoot?.name||'—'} · Player of Year: ${out.playerOfYear?.name||'—'} · Best Young Player: ${out.bestYoung?.name||'—'}`});return out}
function coefficientFinalize(s){const g=s.gameState,k=country(s);g.europeCoefficients??={tr:14.2,gb:18.6,de:17.7,es:18.4,it:17.9,fr:14.1};const pts=Number(g.europeSeasonPoints?.[k]||0);g.europeCoefficients[k]=Math.max(1,Math.round((Number(g.europeCoefficients[k]||0)+pts/10)*100)/100);g.europeCountryRank=Object.entries(g.europeCoefficients).sort((a,b)=>b[1]-a[1]).map(([code,coefficient],i)=>({rank:i+1,code,coefficient}));}
function seasonSnapshot(s,r){const g=s.gameState,c=ensure(s);const snap={season:g.season,club:g.club?.name,position:r.position,target:r.target,champion:r.champion,promoted:r.promoted||[],relegated:r.relegated||[],trophies:(g.trophies||[]).slice(),europe:g.europeQualification?.competition||null,date:g.date};c.seasons.unshift(snap);c.seasons=c.seasons.slice(0,30);if(r.champion)c.trophies.unshift({name:g.fixtures?.leagueName||'LİG ŞAMPİYONLUĞU',season:g.season});}
function render(){const s=read();if(!s?.gameState?.club)return;const g=s.gameState,c=ensure(s),host=document.getElementById('careerHistoryPanel')||document.getElementById('dashboard');if(!host)return;let b=document.getElementById('careerLegacyPanel');if(!b){b=document.createElement('section');b.id='careerLegacyPanel';host.appendChild(b)}const seasons=c.seasons||[],a=g.seasonAwards;b.innerHTML=`<div class="media-card career-legacy"><div class="media-head"><div><span class="eyebrow">NEXORA CAREER ARCHIVE</span><h3>SEASONS & LEGACY</h3><p>${esc(g.managerName||'Manager')} · ${esc(g.club.name)}</p></div><span class="news-badge">${seasons.length} SEASONS</span></div><div class="legacy-timeline">${seasons.length?seasons.map(x=>`<div class="legacy-season"><div class="legacy-dot"></div><div><b>${esc(x.season)}</b><strong>${esc(x.club||'Club')} · ${x.champion?'🏆 CHAMPION':`#${x.position}`}</strong><small>Target #${x.target} · Europe ${esc(x.europe||'—')} · Promoted ${x.promoted?.length||0} · Relegated ${x.relegated?.length||0}</small></div></div>`).join(''):'<div class="career-empty">2026/27 is the opening chapter.</div>'}</div>${a?`<div class="award-grid"><div><b>🥇</b><span>ALTIN AYAKKABI</span><strong>${esc(a.goldenBoot?.name||'—')}</strong></div><div><b>⭐</b><span>YILIN OYUNCUSU</span><strong>${esc(a.playerOfYear?.name||'—')}</strong></div><div><b>🎓</b><span>EN İYİ GENÇ</span><strong>${esc(a.bestYoung?.name||'—')}</strong></div><div><b>👔</b><span>YILIN TEKNİK DİREKTÖRÜ</span><strong>${esc(a.managerOfYear?.name||'—')}</strong></div></div>`:''}</div>`}
function finalize(r){const s=read();if(!s?.gameState)return;awards(s);coefficientFinalize(s);seasonSnapshot(s,r);save(s);render();window.dispatchEvent(new CustomEvent('nexora:legacy-updated',{detail:{season:s.gameState.season}}))}
window.NEXORA_LEGACY={ensure,finalize,awards,coefficientFinalize,render};window.addEventListener('nexora:match-event',e=>{const s=read();if(!s)return;recordMatch(s,e.detail);europeanPoints(s,e.detail);save(s)});['nexora:career-ready','nexora:season-reviewed','nexora:new-season'].forEach(ev=>window.addEventListener(ev,()=>setTimeout(render,120)));setTimeout(render,300);
})();
