(()=>{
const K='nexoraCareer';
const get=()=>{try{return JSON.parse(localStorage.getItem(K)||'null')}catch{return null}};
const put=s=>{localStorage.setItem(K,JSON.stringify(s));localStorage.setItem('nexoraGameState',JSON.stringify(s.gameState))};
const addDay=(d,n)=>{const x=new Date(d+'T00:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)};
const diff=(a,b)=>Math.max(0,Math.round((new Date(b)-new Date(a))/86400000));
const ensure=s=>{s.gameState.finance||={wageBill:0,wageBudget:Math.max(50000,Math.round((s.gameState.money||0)*.025)),lastPaid:s.gameState.date,totalPaid:0};s.gameState.media||={news:[],events:[]};s.gameState.world||={lastNews:null,seed:0};s.gameState.finance.wageBill=(s.squad||[]).reduce((n,p)=>n+Number(p.wage||0),0);return s};
function news(s,title,tag,detail){ensure(s);s.gameState.media.news.unshift({id:Date.now()+Math.random(),title,tag,detail,date:s.gameState.date});s.gameState.media.news=s.gameState.media.news.slice(0,12)}
function daily(s){ensure(s);if(s.gameState.world.lastNews===s.gameState.date)return;s.gameState.world.lastNews=s.gameState.date;s.gameState.world.seed++;const p=[['LEAGUE','Lig gündemi hareketli','Sezon hazırlıkları hız kazanıyor.'],['WORLD','Transfer masası ısınıyor','Scout ekipleri yeni isimleri takip ediyor.'],['SUPPORTERS','Tribünlerde beklenti','Taraftarlar yeni sezon planını konuşuyor.'],['SCOUTING','Genç yetenekler radar altında','Akademilerden yeni adaylar çıkıyor.']];const x=p[s.gameState.world.seed%p.length];news(s,x[1],x[0],`${s.gameState.club?.name||'Kulüp'} · ${x[2]}`)}
function pay(s){const f=s.gameState.finance,n=diff(f.lastPaid||s.gameState.date,s.gameState.date);if(n<7)return;const weeks=Math.floor(n/7),cost=weeks*f.wageBill;f.lastPaid=addDay(f.lastPaid,weeks*7);if(cost){s.gameState.money-=cost;f.totalPaid+=cost;news(s,'Haftalık oyuncu maaşları ödendi','FINANCE',`${weeks} hafta · €${cost.toLocaleString('tr-TR')} bütçeden ayrıldı.`)}}
function youth(s){const a=s.gameState.facilities?.academy;if(!a?.owned||!a.signed?.length)return;const last=a.lastGrowthDate||s.gameState.date,w=Math.floor(diff(last,s.gameState.date)/7);if(!w)return;const bonus=(s.gameState.facilities?.training?.level||0)*.08+(a.level||0)*.1;a.signed.forEach(p=>{for(let i=0;i<w;i++){p.rating=Math.min(Number(p.potential)||70,Math.round(((Number(p.rating)||50)+.15+bonus)*10)/10);p.value=Math.max(Number(p.value)||50000,Math.round(p.rating*p.rating*900))}});a.lastGrowthDate=addDay(last,w*7)}
function step(s){ensure(s);window.NEXORA_FACILITIES?.complete?.();window.NEXORA_STADIUM?.completeConstruction?.();youth(s);pay(s);daily(s);put(s)}
function advance(n=1){const s=get();if(!s?.gameState?.club)return null;for(let i=0;i<Math.max(1,Math.min(30,n));i++){s.gameState.date=addDay(s.gameState.date,1);step(s)}put(s);window.NEXORA_FACILITIES?.render?.();window.NEXORA_MEDIA?.render?.();window.NEXORA_TRANSFER?.render?.();window.dispatchEvent(new CustomEvent('nexora:day-advanced',{detail:{date:s.gameState.date}}));render(s);return s.gameState.date}
function render(s){ensure(s);const d=document.getElementById('dashboard');if(!d)return;let h=document.getElementById('careerClock');if(!h){h=document.createElement('section');h.id='careerClock';h.className='game-finance';(document.querySelector('.dashboard-panels')||d).insertAdjacentElement('afterend',h)}const f=s.gameState.finance;h.innerHTML=`<div><span class="eyebrow">CAREER CLOCK / CLUB FINANCE</span><h3>FINANCIAL PULSE</h3></div><div class="finance-grid"><div><span>TRANSFER BUDGET</span><b>€${Number(s.gameState.money||0).toLocaleString('tr-TR')}</b></div><div><span>WAGE BILL / WEEK</span><b>€${Number(f.wageBill||0).toLocaleString('tr-TR')}</b></div><div><span>WAGE BUDGET</span><b>€${Number(f.wageBudget||0).toLocaleString('tr-TR')}</b></div><div><span>HEADROOM</span><b>€${Math.max(0,f.wageBudget-f.wageBill).toLocaleString('tr-TR')}</b></div></div><div class="time-controls"><span><b>${s.gameState.date}</b> · ${s.gameState.season||'2026/27'}</span><button class="primary" id="nextCareerDay">SONRAKİ GÜNE İLERLE →</button><button class="secondary" id="nextCareerWeek">+7 GÜN</button></div>`;h.querySelector('#nextCareerDay').onclick=()=>advance(1);h.querySelector('#nextCareerWeek').onclick=()=>advance(7)}
window.NEXORA_CAREER_LOOP={advanceDay:()=>advance(1),advanceWeek:()=>advance(7),advance,refresh:()=>{const s=get();if(s){ensure(s);put(s);render(s)}}};
window.addEventListener('load',()=>{const s=get();if(s){ensure(s);put(s);render(s)}});window.addEventListener('nexora:career-ready',()=>{const s=get();if(s){ensure(s);put(s);render(s)}});window.addEventListener('nexora:transfer-updated',()=>{const s=get();if(s){ensure(s);put(s);render(s)}});
})();