(()=>{
const K='nexoraCareer';
const get=()=>{try{return JSON.parse(localStorage.getItem(K)||'null')}catch{return null}};
const put=s=>{localStorage.setItem(K,JSON.stringify(s));localStorage.setItem('nexoraGameState',JSON.stringify(s.gameState))};
const addDay=(d,n)=>{const x=new Date(d+'T00:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)};
const diff=(a,b)=>Math.max(0,Math.round((new Date(b)-new Date(a))/86400000));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const money=n=>`€${Math.round(n||0).toLocaleString('tr-TR')}`;
function ensure(s){const g=s.gameState;g.finance||={};Object.assign(g.finance,{wageBill:0,wageBudget:g.finance.wageBudget||Math.max(50000,Math.round((g.money||0)*.025)),lastPaid:g.finance.lastPaid||g.date,totalPaid:g.finance.totalPaid||0,totalOperatingPaid:g.finance.totalOperatingPaid||0});g.media||={news:[],events:[]};g.world||={lastNews:null,seed:0};g.clubOps||={lastDate:g.date,facilities:{led:55,pitch:72,lines:88,lights:64},staff:{headCoach:1,assistant:1,scout:1,physio:1,groundskeepers:2,security:2,operations:2},alerts:[],fanMood:62};g.clubOps.facilities||={led:55,pitch:72,lines:88,lights:64};g.clubOps.staff||={headCoach:1,assistant:1,scout:1,physio:1,groundskeepers:2,security:2,operations:2};g.clubOps.alerts||=[];g.dialogue||={history:[]};g.matchContext||={refereeErrors:0,appeals:0,warmups:[]};s.gameState.finance.wageBill=(s.squad||[]).reduce((n,p)=>n+Number(p.wage||0),0);return s}
function news(s,title,tag,detail){ensure(s);s.gameState.media.news.unshift({id:Date.now()+Math.random(),title,tag,detail,date:s.gameState.date});s.gameState.media.news=s.gameState.media.news.slice(0,12)}
function dailyNews(s){ensure(s);if(s.gameState.world.lastNews===s.gameState.date)return;s.gameState.world.lastNews=s.gameState.date;s.gameState.world.seed++;const p=[['LEAGUE','Lig gündemi hareketli','Sezon hazırlıkları hız kazanıyor.'],['WORLD','Transfer masası ısınıyor','Scout ekipleri yeni isimleri takip ediyor.'],['SUPPORTERS','Tribünlerde beklenti','Taraftarlar yeni sezon planını konuşuyor.'],['SCOUTING','Genç yetenekler radar altında','Akademilerden yeni adaylar çıkıyor.']];const x=p[s.gameState.world.seed%p.length];news(s,x[1],x[0],`${s.gameState.club?.name||'Kulüp'} · ${x[2]}`)}
function operations(s,days){ensure(s);const g=s.gameState,o=g.clubOps,f=o.facilities,st=o.staff;const staffWeek=st.headCoach*24000+st.assistant*13000+st.scout*12000+st.physio*11000+st.groundskeepers*7500+st.security*6500+st.operations*6000;const utilities=1800+(f.lights>70?900:400)+(f.led>70?700:250);const maintenance=700+Math.max(0,70-f.pitch)*35+Math.max(0,70-f.lines)*22;const stadium=500+Math.max(0,(g.stadium?.capacity||5000)-5000)*.045;g.finance.staffPayroll=staffWeek;g.finance.utilities=utilities;g.finance.maintenance=Math.round(maintenance);g.finance.stadiumMaintenance=Math.round(stadium);g.finance.dailyOperatingCost=Math.round(staffWeek/7+utilities+maintenance+stadium);const cost=Math.round(g.finance.dailyOperatingCost*days);g.money-=cost;g.finance.totalOperatingPaid+=cost;f.led=clamp(f.led-days*.11,0,100);f.pitch=clamp(f.pitch-days*.16,0,100);f.lines=clamp(f.lines-days*.13,0,100);f.lights=clamp(f.lights-days*.09,0,100);if(f.led<35&&!o.alerts.some(a=>a.type==='led')){o.alerts.unshift({type:'led',date:g.date,text:'LED sistemi kritik seviyede. Yayın ve atmosfer kalitesi düşüyor.'})}if(f.pitch<40&&!o.alerts.some(a=>a.type==='pitch'))o.alerts.unshift({type:'pitch',date:g.date,text:'Çim kalitesi kritik. Saha bakımına yatırım yap.'});if(f.lines<45&&!o.alerts.some(a=>a.type==='lines'))o.alerts.unshift({type:'lines',date:g.date,text:'Saha çizgileri silik. Organizasyon uyarısı riski var.'});if(f.lights<40&&!o.alerts.some(a=>a.type==='lights'))o.alerts.unshift({type:'lights',date:g.date,text:'Stadyum aydınlatması yetersiz. Maç organizasyonu riski var.'});if(f.pitch<25||f.lights<25){const fine=25000;g.money-=fine;news(s,'Stadyum organizasyon cezası','DISCIPLINE',`Tesis kalitesi minimum seviyenin altına indi. Ceza: ${money(fine)}`);o.alerts.unshift({type:'fine',date:g.date,text:`Federasyon cezası: ${money(fine)}`})}o.alerts=o.alerts.slice(0,8)}
function pay(s){const f=s.gameState.finance,n=diff(f.lastPaid||s.gameState.date,s.gameState.date);if(n<7)return;const weeks=Math.floor(n/7),cost=weeks*f.wageBill;f.lastPaid=addDay(f.lastPaid,weeks*7);if(cost){s.gameState.money-=cost;f.totalPaid+=cost;news(s,'Haftalık oyuncu maaşları ödendi','FINANCE',`${weeks} hafta · ${money(cost)} bütçeden ayrıldı.`)}}
function youth(s){const a=s.gameState.facilities?.academy;if(!a?.owned||!a.signed?.length)return;const last=a.lastGrowthDate||s.gameState.date,w=Math.floor(diff(last,s.gameState.date)/7);if(!w)return;const bonus=(s.gameState.facilities?.training?.level||0)*.08+(a.level||0)*.1;a.signed.forEach(p=>{for(let i=0;i<w;i++){p.rating=Math.min(Number(p.potential)||70,Math.round(((Number(p.rating)||50)+.15+bonus)*10)/10);p.value=Math.max(Number(p.value)||50000,Math.round(p.rating*p.rating*900))}});a.lastGrowthDate=addDay(last,w*7)}
function step(s){ensure(s);window.NEXORA_FACILITIES?.complete?.();window.NEXORA_STADIUM?.completeConstruction?.();operations(s,1);youth(s);pay(s);dailyNews(s);put(s)}
function advance(n=1){const s=get();if(!s?.gameState?.club)return null;for(let i=0;i<Math.max(1,Math.min(30,n));i++){s.gameState.date=addDay(s.gameState.date,1);step(s)}put(s);window.NEXORA_FACILITIES?.render?.();window.NEXORA_MEDIA?.render?.();window.NEXORA_TRANSFER?.render?.();window.NEXORA_STADIUM?.refresh?.();window.dispatchEvent(new CustomEvent('nexora:day-advanced',{detail:{date:s.gameState.date}}));render(s);return s.gameState.date}
function render(s){ensure(s);const d=document.getElementById('dashboard');if(!d)return;let h=document.getElementById('careerClock');if(!h){h=document.createElement('section');h.id='careerClock';h.className='game-finance';(document.querySelector('.dashboard-panels')||d).insertAdjacentElement('afterend',h)}const f=s.gameState.finance,o=s.gameState.clubOps,fac=o.facilities,staff=o.staff;h.innerHTML=`<div><span class="eyebrow">CAREER CLOCK / CLUB FINANCE</span><h3>FINANCIAL PULSE</h3></div><div class="finance-grid"><div><span>TRANSFER BUDGET</span><b>${money(s.gameState.money)}</b></div><div><span>WAGE BILL / WEEK</span><b>${money(f.wageBill)}</b></div><div><span>DAILY OPERATIONS</span><b>${money(f.dailyOperatingCost)}</b></div><div><span>WAGE BUDGET</span><b>${money(f.wageBudget)}</b></div></div><div class="ops-mini"><span>ELEKTRİK/SU ${money(f.utilities)}</span><span>PERSONEL ${money(f.staffPayroll)}/HF</span><span>LED ${Math.round(fac.led)}%</span><span>ÇİM ${Math.round(fac.pitch)}%</span><span>ÇİZGİ ${Math.round(fac.lines)}%</span><span>IŞIK ${Math.round(fac.lights)}%</span><span>PERSONEL ${Object.values(staff).reduce((a,b)=>a+b,0)}</span></div><div class="time-controls"><span><b>${s.gameState.date}</b> · ${s.gameState.season||'2026/27'}</span><button class="primary" id="nextCareerDay">SONRAKİ GÜNE İLERLE →</button><button class="secondary" id="nextCareerWeek">+7 GÜN</button></div>`;h.querySelector('#nextCareerDay').onclick=()=>advance(1);h.querySelector('#nextCareerWeek').onclick=()=>advance(7)}
window.NEXORA_CAREER_LOOP={advanceDay:()=>advance(1),advanceWeek:()=>advance(7),advance,refresh:()=>{const s=get();if(s){ensure(s);put(s);render(s)}}};
window.addEventListener('load',()=>{const s=get();if(s){ensure(s);put(s);render(s)}});window.addEventListener('nexora:career-ready',()=>{const s=get();if(s){ensure(s);put(s);render(s)}});window.addEventListener('nexora:transfer-updated',()=>{const s=get();if(s){ensure(s);put(s);render(s)}});
})();