(()=>{
const K='nexoraCareer';
const second={tr:['Bursa 1963','Izmit Korfez','Eskisehir 26','Samsun Yildiz','Kayseri Erciyes','Adana Gucu','Antalya Kale','Gaziantep Birlik'],gb:['Birmingham Athletic','Derby Borough','Norwich City','Coventry Royal','Middlesbrough','Blackburn Rovers','Stoke United','Watford'],de:['Nurnberg 1905','Hannover Nord','Dusseldorf 95','Karlsruhe','Kaiserslautern','Rostock','Paderborn','Furth'],es:['Tenerife Real','Sporting Asturias','Malaga CF','Valladolid Norte','Eibar','Levante','Elche','Deportivo Coruna'],it:['Bari Calcio','Palermo Rosa','Brescia','Benevento','Modena','Pescara','Catania','Spezia'],fr:['Caen Normandie','Auxerre Nord','Grenoble','Angers Atlantique','Dijon','Troyes','Amiens','Clermont']};
const read=()=>{try{return JSON.parse(localStorage.getItem(K)||'null')}catch{return null}},save=s=>{localStorage.setItem(K,JSON.stringify(s));localStorage.setItem('nexoraGameState',JSON.stringify(s.gameState))};
function key(s){return window.NEXORA_LEAGUE?.key(s)||s.gameState.country||'tr'}
function ensure(s){s.gameState.world=s.gameState.world||{};s.gameState.world.leaguePools=s.gameState.world.leaguePools||{};return s.gameState.world}
function teams(s,base){const w=ensure(s),k=key(s);w.leaguePools[k] ||= {promoted:[],relegated:[],history:[]};const list=base.slice(),p=w.leaguePools[k].promoted||[];p.forEach((n,i)=>{if(i<list.length)list[list.length-1-i]=n});return list}
function seasonTransition(s,standings){const w=ensure(s),k=key(s),pool=w.leaguePools[k],l=window.NEXORA_LEAGUE?.get(s)||{relegation:3},bottom=(standings||[]).slice(-l.relegation).map(x=>x.name),promoted=(second[k]||[]).filter(n=>!(standings||[]).some(x=>x.name===n)).slice(0,l.relegation);pool.relegated=bottom;pool.promoted=promoted;pool.history.unshift({season:s.gameState.season,promoted,relegated:bottom});pool.history=pool.history.slice(0,8);s.gameState.world.lastMovement={promoted,relegated:bottom};save(s);return{promoted,relegated:bottom}}
function render(){const s=read();if(!s)return;const box=document.getElementById('stadiumDevelopment');if(!box)return;let row=box.querySelector('.nexora-adboards');if(!row){row=document.createElement('div');row.className='nexora-adboards';(box.querySelector('.stadium-visual')||box).appendChild(row)}row.innerHTML=['NEXORA AI','NEXORA88','AHMET EYMEN BAKRAC','BAKRAC SANAYI','NEXORA SPORTS NETWORK'].map(x=>`<div class="nexora-ad"><span>${x}</span></div>`).join('');}
window.NEXORA_WORLD={ensure,teams,seasonTransition,render};window.addEventListener('nexora:new-season',()=>setTimeout(render,100));window.addEventListener('nexora:career-ready',()=>setTimeout(render,100));window.addEventListener('load',()=>setTimeout(render,150));})();