(()=>{
const L={
 tr:{name:'Türkçe',lines:{start:'Maç başladı! Tribünlerde büyük bir heyecan var.',pass:['Orta sahada top dolaşıyor.','Takım paslarla oyunu kuruyor.','Güzel bir pas bağlantısı.'],attack:['Tehlikeli bir atak gelişiyor!','Kanattan geliyorlar, savunma dikkatli olmalı.','Ceza sahası çevresinde baskı artıyor!'],shot:['Şut geliyor!','Kaleyi yokladı, kaleci hazır.','Çok sert bir vuruş!'],goal:['GOOOOL! İnanılmaz bir an!','GOOOL! Tribünler ayağa kalktı!','Ağlar havalandı! Harika bitiriş!'],duel:['İkili mücadele çok sert!','Top için büyük bir savaş var.'],save:['KALECİ! Muhteşem bir kurtarış!','Kaleci gole izin vermedi!'],card:['Hakem kartını gösteriyor.','Faul sonrası hakem oyunu durdurdu.'],end:['Hakemin son düdüğü! Maç sona erdi.']},crowd:{win:'Tribünler zaferi kutluyor!',draw:'Tribünlerde temkinli bir memnuniyet var.',loss:'Tribünlerde hayal kırıklığı hissediliyor.'}},
 en:{name:'English',lines:{start:'Kick-off! The stadium is full of anticipation.',pass:['The ball is moving through midfield.','They are building patiently with possession.','A sharp passing combination.'],attack:['A dangerous attack is developing!','They come down the wing. The defence must stay alert.','Pressure is building around the box!'],shot:['The shot is coming!','A strike towards goal, but the keeper is ready.','What a powerful effort!'],goal:['GOOOAL! What a moment!','GOAL! The whole stadium erupts!','Into the net! A brilliant finish!'],duel:['A fierce battle for the ball!','A strong duel in midfield.'],save:['THE KEEPER! An outstanding save!','The goalkeeper denies the goal!'],card:['The referee reaches for a card.','The referee stops play after a foul.'],end:['Full time! The final whistle goes.']},crowd:{win:'The stands are celebrating the victory!',draw:'A cautious reaction around the stadium.',loss:'Disappointment is spreading through the stands.'}},
 de:{name:'Deutsch',lines:{start:'Anpfiff! Das Stadion ist voller Spannung.',pass:['Der Ball läuft durch das Mittelfeld.','Die Mannschaft baut geduldig auf.','Eine schöne Passkombination.'],attack:['Ein gefährlicher Angriff entwickelt sich!','Der Angriff kommt über die Seite.','Der Druck am Strafraum steigt!'],shot:['Der Schuss kommt!','Ein Abschluss aufs Tor, der Keeper ist bereit.','Was für ein harter Schuss!'],goal:['TOOOOR! Was für ein Moment!','TOR! Das ganze Stadion explodiert!','Der Ball zappelt im Netz!'],duel:['Ein harter Zweikampf um den Ball!','Ein intensives Duell im Mittelfeld.'],save:['DER KEEPER! Eine fantastische Parade!','Der Torwart verhindert das Tor!'],card:['Der Schiedsrichter zeigt eine Karte.','Nach einem Foul wird das Spiel unterbrochen.'],end:['Abpfiff! Das Spiel ist vorbei.']},crowd:{win:'Die Ränge feiern den Sieg!',draw:'Vorsichtige Reaktionen im Stadion.',loss:'Enttäuschung macht sich auf den Rängen breit.'}},
 es:{name:'Español',lines:{start:'¡Comienza el partido! El estadio está expectante.',pass:['El balón circula por el centro del campo.','El equipo construye con paciencia.','Una gran combinación de pases.'],attack:['¡Se desarrolla un ataque peligroso!','Llegan por la banda.','¡Aumenta la presión cerca del área!'],shot:['¡Disparo!','Remate hacia la portería, el portero está preparado.','¡Qué disparo tan potente!'],goal:['¡GOOOOL! ¡Qué momento!','¡GOOOL! ¡Todo el estadio se levanta!','¡El balón acaba en la red!'],duel:['¡Duro duelo por el balón!','Un intenso duelo en el centro.'],save:['¡EL PORTERO! ¡Qué paradón!','¡El guardameta evita el gol!'],card:['El árbitro muestra una tarjeta.','El árbitro detiene el juego tras una falta.'],end:['¡Final del partido! Suena el silbato.']},crowd:{win:'¡La grada celebra la victoria!',draw:'Reacción prudente en el estadio.',loss:'La decepción se siente en las gradas.'}},
 pt:{name:'Português',lines:{start:'Começa o jogo! O estádio está em expectativa.',pass:['A bola circula pelo meio-campo.','A equipe constrói com paciência.','Boa combinação de passes.'],attack:['Um ataque perigoso está se formando!','Eles avançam pela ala.','A pressão aumenta perto da área!'],shot:['Vem o chute!','Finalização ao gol, o goleiro está preparado.','Que chute forte!'],goal:['GOOOOL! Que momento!','GOOOL! O estádio inteiro explode!','A bola está na rede!'],duel:['Uma disputa intensa pela bola!','Um duelo forte no meio-campo.'],save:['O GOLEIRO! Uma defesa fantástica!','O goleiro evita o gol!'],card:['O árbitro mostra um cartão.','O árbitro para o jogo após uma falta.'],end:['Fim de jogo! Apita o árbitro.']},crowd:{win:'A torcida comemora a vitória!',draw:'Reação cautelosa no estádio.',loss:'A decepção toma conta das arquibancadas.'}}
};
const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const pick=a=>a[Math.floor(Math.random()*a.length)];
function lang(){return window.NEXORA_I18N?.language||'tr'}
function data(){return L[lang()]||L.tr}
let last='',timer=null;
function mount(){if(document.getElementById('liveCommentary'))return;const el=document.createElement('section');el.id='liveCommentary';el.className='live-commentary';el.innerHTML='<div class="commentary-head"><span>🎙 LIVE COMMENTARY</span><b id="commentaryLang">TR</b></div><div id="commentaryText">—</div><div id="commentaryCrowd">—</div>';const target=document.getElementById('matchLog')?.parentElement||document.getElementById('matchStage')||document.body;target.appendChild(el)}
function show(text,crowd=''){mount();const el=document.getElementById('commentaryText'),cr=document.getElementById('commentaryCrowd');if(!el)return;el.classList.remove('commentary-pulse');void el.offsetWidth;el.classList.add('commentary-pulse');el.textContent=text;cr.textContent=crowd||'';document.getElementById('commentaryLang').textContent=data().name.toUpperCase();last=text}
function start(){show(data().lines.start);}
function event(type){const d=data().lines;if(type==='goal'){show(pick(d.goal),'🔥 '+pick(data().crowd.win));return}if(type==='shot'){show(pick(d.shot));return}if(type==='pass'){show(pick(d.pass));return}if(type==='duel'){show(pick(d.duel));return}if(type==='save'){show(pick(d.save));return}if(type==='card'){show(pick(d.card));return}if(type==='attack'){show(pick(d.attack));return}if(type==='end'){show(d.end[Math.floor(Math.random()*d.end.length)]);}}
function observe(){const log=document.getElementById('matchLog');if(!log)return;let old='';new MutationObserver(()=>{const text=log.textContent||'';if(text===old)return;old=text;const low=text.toLowerCase();if(/goal|gooo|gol!|gool/.test(low))event('goal');else if(/şut|shot|abschluss|disparo|chute/.test(low))event('shot');else if(/pası|pas |pass|pase|passe/.test(low))event('pass');else if(/kazandı|duel|mücadele|duelo|disputa/.test(low))event('duel');else if(/kart|card|tarjeta|karte|cartão/.test(low))event('card');}).observe(log,{childList:true,subtree:true,characterData:true})}
function init(){mount();setTimeout(observe,300);window.addEventListener('nexora:language-changed',()=>{if(last)show(last);});window.addEventListener('nexora:match-event',e=>event(e.detail?.type));window.addEventListener('nexora:match-start',start);window.addEventListener('nexora:match-fulltime',()=>event('end'));}
window.NEXORA_COMMENTARY={start,event,mount};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();