/* NEXORA FOOTBALL MANAGER — DATA LAYER */
const NEXORA_DATA={
 version:'1.1.0',
 schema:'club/player attributes -> simulation inputs',
 leagues:{tr:{name:'Türkiye Süper Ligi',country:'Türkiye',europe:{cl:3,el:2,ec:1}},gb:{name:'Premier League',country:'İngiltere',europe:{cl:5,el:2,ec:1}},de:{name:'Bundesliga',country:'Almanya',europe:{cl:5,el:2,ec:1}},es:{name:'La Liga',country:'İspanya',europe:{cl:5,el:2,ec:1}},it:{name:'Serie A',country:'İtalya',europe:{cl:5,el:2,ec:1}},fr:{name:'Ligue 1',country:'Fransa',europe:{cl:3,el:2,ec:1}}},
 clubs:[
  {id:'ays',name:'Anadolu Yıldızı SK',city:'Bursa',code:'AYS',style:'Balanced',league:'Nexora Super League',leagueCountry:'tr',difficulty:'NORMAL',budget:5000000,reputation:52,stadiumCapacity:5000,colors:['#d71920','#ffffff']},
  {id:'mrk',name:'Marmara Kartalları',city:'İstanbul',code:'MRK',style:'Attacking',league:'Nexora Super League',leagueCountry:'tr',difficulty:'HARD',budget:6500000,reputation:64,stadiumCapacity:8000,colors:['#102a43','#ffffff']},
  {id:'eaf',name:'Ege Ateşi FK',city:'İzmir',code:'EAF',style:'Technical',league:'Nexora Super League',leagueCountry:'tr',difficulty:'NORMAL',budget:5500000,reputation:58,stadiumCapacity:7000,colors:['#f36f21','#0b3d91']},
  {id:'tb26',name:'Trakya Birlik 1926',city:'Edirne',code:'TB26',style:'Defensive',league:'Nexora Super League',leagueCountry:'tr',difficulty:'CHALLENGE',budget:3200000,reputation:45,stadiumCapacity:5000,colors:['#1f7a4c','#ffffff']},
  {id:'ib',name:'İstanbul Boğazı',city:'İstanbul',code:'IBG',style:'Attacking',league:'Nexora Super League',leagueCountry:'tr',difficulty:'HARD',budget:9000000,reputation:70,stadiumCapacity:12000,colors:['#0b1f3a','#d4af37']},
  {id:'kfk',name:'Karadeniz FK',city:'Trabzon',code:'KRF',style:'Balanced',league:'Nexora Super League',leagueCountry:'tr',difficulty:'NORMAL',budget:5700000,reputation:59,stadiumCapacity:8500,colors:['#176b4d','#ffffff']},
  {id:'b1910',name:'Başkent 1910',city:'Ankara',code:'B10',style:'Technical',league:'Nexora Super League',leagueCountry:'tr',difficulty:'NORMAL',budget:6100000,reputation:61,stadiumCapacity:9000,colors:['#8b1e2d','#ffffff']},
  {id:'akb',name:'Akdeniz Birliği',city:'Antalya',code:'AKB',style:'Attacking',league:'Nexora Super League',leagueCountry:'tr',difficulty:'NORMAL',budget:5800000,reputation:56,stadiumCapacity:7500,colors:['#e65c24','#ffffff']},
  {id:'kps',name:'Kapadokya Spor',city:'Nevşehir',code:'KPS',style:'Defensive',league:'Nexora Super League',leagueCountry:'tr',difficulty:'CHALLENGE',budget:3500000,reputation:43,stadiumCapacity:4500,colors:['#7b4a2e','#e7c99b']},
  {id:'dys',name:'Doğu Yıldızları',city:'Erzurum',code:'DYS',style:'Defensive',league:'Nexora Super League',leagueCountry:'tr',difficulty:'CHALLENGE',budget:3000000,reputation:40,stadiumCapacity:5000,colors:['#174a7e','#ffffff']},
  {id:'m1907',name:'Marmara 1907',city:'Kocaeli',code:'M19',style:'Balanced',league:'Nexora Super League',leagueCountry:'tr',difficulty:'NORMAL',budget:5200000,reputation:53,stadiumCapacity:6500,colors:['#111111','#d9b44a']},
  {id:'cuk',name:'Çukurova FK',city:'Adana',code:'CUK',style:'Attacking',league:'Nexora Super League',leagueCountry:'tr',difficulty:'NORMAL',budget:5400000,reputation:55,stadiumCapacity:7000,colors:['#c92a2a','#f4d35e']},
  {id:'ban',name:'Batı Anadolu',city:'Manisa',code:'BAN',style:'Technical',league:'Nexora Super League',leagueCountry:'tr',difficulty:'NORMAL',budget:4700000,reputation:49,stadiumCapacity:6000,colors:['#31572c','#ffffff']},
  {id:'k1967',name:'Karadeniz 1967',city:'Samsun',code:'K67',style:'Balanced',league:'Nexora Super League',leagueCountry:'tr',difficulty:'NORMAL',budget:4900000,reputation:51,stadiumCapacity:7000,colors:['#d62828','#ffffff']},
  {id:'ias',name:'İç Anadolu SK',city:'Konya',code:'IAS',style:'Defensive',league:'Nexora Super League',leagueCountry:'tr',difficulty:'NORMAL',budget:5100000,reputation:50,stadiumCapacity:7500,colors:['#2f6b3f','#ffffff']},
  {id:'ak07',name:'Akdeniz 07',city:'Mersin',code:'A07',style:'Attacking',league:'Nexora Super League',leagueCountry:'tr',difficulty:'CHALLENGE',budget:3800000,reputation:44,stadiumCapacity:5500,colors:['#1976a3','#ffffff']},
  {id:'eb',name:'Ege Birlik',city:'Denizli',code:'EGB',style:'Technical',league:'Nexora Super League',leagueCountry:'tr',difficulty:'CHALLENGE',budget:3600000,reputation:42,stadiumCapacity:5000,colors:['#2455a4','#ffffff']},
  {id:'bog',name:'Boğaziçi FK',city:'İstanbul',code:'BGF',style:'Balanced',league:'Nexora Super League',leagueCountry:'tr',difficulty:'HARD',budget:7200000,reputation:63,stadiumCapacity:9500,colors:['#4b1f6f','#ffffff']}
 ],
 names:['Emir Kaya','Mert Arslan','Bora Yılmaz','Kerem Demir','Efe Aydın','Can Korkmaz','Arda Şen','Yiğit Koç','Deniz Aksoy','Baran Çelik','Ozan Erdem','Ali Tunç','Eren Güneş','Kaan Polat','Berk Özkan','Umut Kaplan','Doruk Keskin','Metehan Kurt','Selim Çetin','Furkan Işık','Onur Taş','Burak Vural'],
 positions:['GK','GK','RB','CB','CB','LB','DM','CM','CM','AM','RW','LW','ST','ST','CB','RB','LB','CM','DM','RW','LW','ST'],
 positionWeights:{GK:{pace:-8,passing:2,shooting:-18,defending:18,dribbling:-8,physical:7,vision:4,stamina:3},CB:{pace:-1,passing:4,shooting:-10,defending:14,dribbling:-2,physical:10,vision:3,stamina:5},RB:{pace:8,passing:5,shooting:-4,defending:7,dribbling:6,physical:4,vision:3,stamina:9},LB:{pace:8,passing:5,shooting:-4,defending:7,dribbling:6,physical:4,vision:3,stamina:9},DM:{pace:-1,passing:8,shooting:-2,defending:9,dribbling:2,physical:8,vision:9,stamina:8},CM:{pace:3,passing:10,shooting:3,defending:3,dribbling:7,physical:4,vision:10,stamina:9},AM:{pace:5,passing:9,shooting:7,defending:-4,dribbling:10,physical:-2,vision:11,stamina:5},RW:{pace:10,passing:5,shooting:5,defending:-6,dribbling:12,physical:-1,vision:5,stamina:6},LW:{pace:10,passing:5,shooting:5,defending:-6,dribbling:12,physical:-1,vision:5,stamina:6},ST:{pace:6,passing:0,shooting:13,defending:-8,dribbling:7,physical:7,vision:2,stamina:4}},
 leagueAccess(s){const saved=s?.gameState?.europeAccessNextSeason;if(saved?.country==='tr')return saved;const co=Number(window.NEXORA_COEFFICIENTS?.get?.(s)||14.2),cl=co>=18?5:co>=16?4:3;return{country:'tr',cl,el:2,ec:1,total:cl+3,coefficient:co}},
 createSquad(club){const clubStyle=club?.style||'Balanced',base=clubStyle==='Attacking'?71:clubStyle==='Defensive'?68:clubStyle==='Technical'?70:69,styleBonus=clubStyle==='Attacking'?{passing:2,shooting:2}:clubStyle==='Technical'?{passing:3,dribbling:3,vision:2}:clubStyle==='Defensive'?{defending:3,physical:2}:{};return this.names.map((name,i)=>{const pos=this.positions[i],w=this.positionWeights[pos],seed=(i*17+11)%13,stat=n=>Math.max(45,Math.min(90,base+((i*7)%9)-4+(w[n]||0)+(styleBonus[n]||0)+(seed%5)-2)),age=18+(i*3)%15,potential=Math.max(stat('passing'),stat('dribbling'),stat('shooting'))+Math.max(3,22-Math.floor(age/2)),rating=Math.round(stat('defending')*.22+stat('passing')*.16+stat('shooting')*.16+stat('dribbling')*.16+stat('physical')*.10+stat('pace')*.10+stat('vision')*.10);return{id:i+1,name,pos,role:pos,age,rating,pace:stat('pace'),passing:stat('passing'),shooting:stat('shooting'),defending:stat('defending'),dribbling:stat('dribbling'),physical:stat('physical'),vision:stat('vision'),stamina:stat('stamina'),fitness:86+((i*5)%14),morale:72+((i*9)%24),potential:Math.min(90,potential),value:Math.round((rating*rating*age<5000?rating*1200:rating*rating*1800)/100)*100,wage:4500+(i*650)}})}};
function getClubData(club){return NEXORA_DATA.clubs.find(c=>c.id===club?.id||c.code===club?.code)||club}
window.NEXORA_DATA=NEXORA_DATA;
window.getClubData=getClubData;
