(()=>{
const K='nexoraCareer',read=()=>JSON.parse(localStorage.getItem(K)||'null'),save=s=>localStorage.setItem(K,JSON.stringify(s));
const rounds=['SON 32','SON 16','ÇEYREK FİNAL','YARI FİNAL','FİNAL'];
const pool={tr:['Bursa 1963','Izmit Korfez','Eskisehir 26','Samsun Yildiz','Kayseri Erciyes','Adana Gucu','Antalya Kale','Gaziantep Birlik','Mersin Liman','Diyarbakir 21','Sakarya Ada','Manisa Ege','Van Kale','Konya Ova','Denizli Horoz','Balikesir 10'],gb:['Birmingham Athletic','Derby Borough','Norwich City','Coventry Royal','Middlesbrough','Blackburn Rovers','Stoke United','Watford','Swansea Coast','Bristol City','Sheffield North','Hull Athletic','Reading','Preston','Millwall','QPR'],de:['Nurnberg 1905','Hannover Nord','Dusseldorf 95','Karlsruhe','Kaiserslautern','Rostock','Paderborn','Furth','Dresden','Bochum','Aachen','Regensburg','Ulm','Munster','Darmstadt','Osnabruck'],es:['Tenerife Real','Sporting Asturias','Malaga CF','Valladolid Norte','Eibar','Levante','Elche','Deportivo Coruna','Zaragoza','Oviedo','Granada','Almeria','Leganes','Huesca','Burgos','Cadiz'],it:['Bari Calcio','Palermo Rosa','Brescia','Benevento','Modena','Pescara','Catania','Spezia','Parma','Pisa','Como','Venezia','Reggiana','Cremonese','Sampdoria','Perugia'],fr:['Caen Normandie','Auxerre Nord','Grenoble','Angers Atlantique','Dijon','Troyes','Amiens','Clermont','Metz','Lorient','Ajaccio','Rodez','Guingamp','Pau','Laval','Annecy']};
function ensure(){const s=read();if(!s?.gameState?.club)return null;if(s.gameState.domesticCup?.season===s.gameState.season)return s.gameState.domesticCup;const code=s.gameState.country||'tr',league=(s.gameState.standings||[]).map(x=>x.name).filter(Boolean),teams=[s.gameState.club.name,...league.filter(x=>x!==s.gameState.club.name),...(pool[code]||pool.tr)];const unique=[...new Set(teams)].slice(0,32).sort(()=>Math.random()-.5);const roundsData={};roundsData[rounds[0]]=pair(unique);s.gameState.domesticCup={name:code==='tr'?'TÜRKİYE KUPASI':'NATIONAL CUP',season:s.gameState.season,round:rounds[0],roundIndex:0,rounds:roundsData,history:[],winner:null};save(s);return s.gameState.domesticCup}
function pair(a){const out=[];for(let i=0;i<a.length;i+=2)out.push({home:a[i],away:a[i+1]||'BYE',played:false,winner:null,homeGoals:null,awayGoals:null});return out}
function currentUserTie(c){return (c.rounds[c.round]||[]).find(r=>r.home===read()?.gameState?.club?.name||r.away===read()?.gameState?.club?.name)}
function nextRound(c){const prev=c.rounds[c.round]||[],w=prev.map(r=>r.winner).filter(Boolean);if(w.length<=1){c.winner=w[0]||c.winner;return false}c.roundIndex=Math.min(rounds.length-1,c.roundIndex+1);c.round=rounds[c.roundIndex];c.rounds[c.round]=pair(w);return true}
function process(e){const s=read(),c=s?.gameState?.domesticCup;if(!s||!c||e?.detail?.type!=='fulltime'||s.gameState.nextCompetition!=='cup')return;const tie=currentUserTie(c);if(!tie)return;const h=Number(e.detail.homeGoals||0),a=Number(e.detail.awayGoals||0);tie.homeGoals=h;tie.awayGoals=a;tie.played=true;tie.winner=h===a?(Math.random()<.5?tie.home:tie.away):h>a?tie.home:tie.away;c.history.unshift({season:c.season,round:c.round,home:tie.home,away:tie.away,score:`${h}-${a}`,winner:tie.winner});s.gameState.nextCompetition='league';if(nextRound(c)){const user=currentUserTie(c);if(user){s.gameState.nextCompetition='cup';s.gameState.nextFixture={id:`cup-${c.season}-${c.round}-${c.roundIndex}`,round:c.round,date:s.gameState.date,home:user.home===s.gameState.club.name,opponent:user.home===s.gameState.club.name?user.away:user.home,opponentId:'cup-opponent',homeName:user.home,awayName:user.away,daysUntil:0}}}else{c.winner=c.winner||tie.winner;s.gameState.trophies=s.gameState.trophies||[];s.gameState.trophies.push({name:c.name,season:c.season,date:s.gameState.date});s.gameState.media??={news:[]};s.gameState.media.news.unshift({date:s.gameState.date,tag:'CUP FINAL',market:'GLOBAL',title:`${c.name} FİNALİ`,detail:`Kupa şampiyonu: ${c.winner}`});}save(s);window.dispatchEvent(new CustomEvent('nexora:cup-updated'));render()}
function prepare(){const s=read(),c=ensure();if(!s||!c)return;const tie=currentUserTie(c);if(!tie||tie.played)return;if(tie.away==='BYE'){tie.played=true;tie.winner=tie.home;nextRound(c);save(s);return}s.gameState.nextCompetition='cup';s.gameState.nextFixture={id:`cup-${c.season}-${c.round}-${c.roundIndex}`,round:c.round,date:s.gameState.date,home:tie.home===s.gameState.club.name,opponent:tie.home===s.gameState.club.name?tie.away:tie.home,opponentId:'cup-opponent',homeName:tie.home,awayName:tie.away,daysUntil:0};save(s)}
function render(){const s=read();if(!s?.gameState?.club)return;const c=ensure(),host=document.getElementById('competitionHub')||document.getElementById('dashboard');if(!host)return;let box=document.getElementById('domesticCup');if(!box){box=document.createElement('section');box.id='domesticCup';host.appendChild(box)}const tie=currentUserTie(c);box.innerHTML=`<div class="cup-panel"><span class="eyebrow">KNOCKOUT FOOTBALL · ${esc(c.season)}</span><h3>🏆 ${esc(c.name)}</h3><div class="cup-meta">${esc(c.round)} · ${c.winner?'CHAMPION: '+esc(c.winner):'32 TAKIMLI BRACKET'}</div><div class="cup-stage-list">${rounds.map((r,i)=>`<span class="${i===c.roundIndex?'active':''} ${i<c.roundIndex?'done':''}">${r}</span>`).join('')}</div><div class="cup-match">${tie?`<small>SENİN MAÇIN</small><b>${esc(tie.home)}</b><span>VS</span><b>${esc(tie.away)}</b><em>${tie.played?'PLAYED':'UPCOMING'}</em>`:'<small>BRACKET</small><b>Sonraki turda eşleşme bekleniyor.</b>'}</div><div class="cup-actions"><button class="primary" id="cupStart">KUPA MAÇINA ÇIK</button><button class="secondary" id="cupDraw">YENİ KURA</button></div></div>`;box.querySelector('#cupStart')?.addEventListener('click',()=>{prepare();window.NEXORA_MATCH_ENGINE?.start?.()});box.querySelector('#cupDraw')?.addEventListener('click',()=>{s.gameState.domesticCup=null;save(s);ensure();render()})}
const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
window.NEXORA_CUP={ensure,render,prepare,process};['nexora:career-ready','nexora:day-advanced','nexora:new-season','nexora:cup-updated'].forEach(e=>window.addEventListener(e,render));window.addEventListener('nexora:match-event',e=>process(e));setTimeout(()=>{ensure();prepare();render()},180);
})();
