(()=>{
const K='nexoraCareer',R=()=>JSON.parse(localStorage.getItem(K)||'null'),W=s=>localStorage.setItem(K,JSON.stringify(s));
const O=['London Royals','Munich 04','Madrid Athletic','Milano Calcio','Paris Union','Amsterdam FC','Lisbon Sporting','Prague Dynamo'];
function start(){const s=R(),q=s?.gameState?.europeQualification;if(!s||!q||q.modern)return;if(q.schedule)return q.modern=true,q.phase='LEAGUE PHASE',next(s);q.modern=true;q.phase='LEAGUE PHASE';q.schedule=O.sort(()=>Math.random()-.5).slice(0,q.competition==='CL'?6:4).map((op,i)=>({opponent:op,home:i%2===0,played:false,user:0,opp:0}));q.matchIndex=0;q.points=0;q.aggregate=0;W(s);next(s)}
function next(s){const q=s.gameState.europeQualification;if(q.eliminated||q.winner)return;let m=q.schedule[q.matchIndex];if(!m){if(q.phase==='LEAGUE PHASE'){q.phase='KNOCKOUT';q.schedule=O.slice(0,4).map((op,i)=>({opponent:op,home:i%2===0,played:false,user:0,opp:0,leg:1}));q.matchIndex=0;q.aggregate=0;m=q.schedule[0]}else return}s.gameState.nextCompetition='europe-modern';s.gameState.nextFixture={id:'eu-'+s.gameState.season+'-'+q.phase+'-'+q.matchIndex+'-'+(m.leg||1),round:q.phase,date:s.gameState.date,home:m.home,opponent:m.opponent,homeName:m.home?s.gameState.club.name:m.opponent,awayName:m.home?m.opponent:s.gameState.club.name,daysUntil:0};W(s)}
function done(e){const s=R(),q=s?.gameState?.europeQualification;if(!s||!q||!q.modern||s.gameState.nextCompetition!=='europe-modern'||e.detail?.type!=='fulltime')return;const m=q.schedule?.[q.matchIndex];if(!m)return;const h=+e.detail.homeGoals||0,a=+e.detail.awayGoals||0;m.user=m.home?h:a;m.opp=m.home?a:h;m.played=true;if(q.phase==='LEAGUE PHASE'){q.points+=m.user>m.opp?3:m.user===m.opp?1:0;q.matchIndex++;if(q.matchIndex>=q.schedule.length){q.phase='KNOCKOUT';q.schedule=O.slice(0,4).map((op,i)=>({opponent:op,home:i%2===0,played:false,user:0,opp:0,leg:1}));q.matchIndex=0;q.aggregate=0}}else{q.aggregate+=m.user-m.opp;if((m.leg||1)===1){m.leg=2;m.played=false;m.home=!m.home}else{if(q.aggregate<0){q.eliminated=true;s.gameState.nextCompetition='league';s.gameState.nextFixture=null}else{q.aggregate=0;q.matchIndex++;if(q.matchIndex>=q.schedule.length){if(q.phase==='KNOCKOUT'){q.phase='QUARTER';q.schedule=O.slice(0,2).map((op,i)=>({opponent:op,home:i%2===0,played:false,user:0,opp:0,leg:1}));q.matchIndex=0}else if(q.phase==='QUARTER'){q.phase='SEMI';q.schedule=O.slice(0,1).map(op=>({opponent:op,home:true,played:false,user:0,opp:0,leg:1}));q.matchIndex=0}else if(q.phase==='SEMI'){q.phase='FINAL';q.schedule=[{opponent:O[0],home:true,played:false,user:0,opp:0,leg:1}];q.matchIndex=0}else{q.winner=true;s.gameState.nextCompetition='league';s.gameState.nextFixture=null;s.gameState.trophies??=[];s.gameState.trophies.push({name:q.competition==='CL'?'UEFA ŞAMPİYONLAR LİGİ':q.competition==='EL'?'UEFA AVRUPA LİGİ':'UEFA KONFERANS LİGİ',season:s.gameState.season,date:s.gameState.date})}}}}}}
if(!q.eliminated&&!q.winner)next(s);W(s);window.dispatchEvent(new CustomEvent('nexora:europe-season-updated'))}
window.NEXORA_EUROPE_SEASON={start,next};window.addEventListener('nexora:europe-qualified',start);window.addEventListener('nexora:match-event',done);setTimeout(()=>{const s=R();if(s?.gameState?.europeQualification)start()},500);
})();
