(() => {
  const TYPES={training:{name:'ANtrenman TESİSİ',key:'training',levels:[{name:'EMPTY LAND',cost:150000,days:14,effect:'Temel antrenman alanı'},{name:'TRAINING GROUND',cost:450000,days:30,effect:'+2 kondisyon / hafta'},{name:'PRO TRAINING CENTRE',cost:1200000,days:60,effect:'+4 gelişim / hafta'},{name:'ELITE ACADEMY CAMPUS',cost:3000000,days:90,effect:'+7 gelişim / hafta'}]},medical:{name:'SAĞLIK MERKEZİ',key:'medical',levels:[{name:'EMPTY LAND',cost:100000,days:10,effect:'Temel sağlık odası'},{name:'CLUB CLINIC',cost:350000,days:25,effect:'Sakatlık toparlanması +'},{name:'MEDICAL CENTRE',cost:900000,days:45,effect:'Sakatlık süresi -20%'},{name:'ELITE MEDICAL CAMPUS',cost:2000000,days:70,effect:'Sakatlık süresi -35%'}]}};
  const money=v=>`€${(v/1000000).toFixed(1)}M`;
  const addDays=(date,days)=>{const d=new Date(`${date}T00:00:00`);d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};
  function ensure(){if(!gameState.facilities)gameState.facilities={training:{level:0,owned:false,construction:null},medical:{level:0,owned:false,construction:null}};return gameState.facilities}
  function levelData(type){const f=ensure()[type], list=TYPES[type].levels;return {f,list,current:list[f.level]||list[0],next:list[f.level+1]}}
  function render(){const host=document.getElementById('clubFacilities');if(!host)return;const f=ensure();host.innerHTML=`<div class="facility-head"><div><span class="eyebrow">CLUB DEVELOPMENT / INFRASTRUCTURE</span><h3>Build the football machine.</h3><p>Buy land, construct facilities and let infrastructure change player development, fitness and recovery.</p></div><span class="eyebrow">LAND + CONSTRUCTION</span></div><div class="facility-grid">${['training','medical'].map(type=>{const d=levelData(type),c=d.f.construction;return `<article class="facility-card"><div class="facility-icon">${type==='training'?'TR':'MD'}</div><span class="eyebrow">${TYPES[type].name}</span><h4>${d.current.name}</h4><p>${d.current.effect}</p><div class="facility-stat"><span>STATUS</span><b>${c?'IN CONSTRUCTION':d.f.owned?'ACTIVE':'NO LAND'}</b></div><div class="facility-stat"><span>LEVEL</span><b>${d.f.level}/${d.list.length-1}</b></div>${c?`<div class="facility-build"><strong>BUILDING</strong><span>${Math.max(0,Math.ceil((new Date(`${c.endDate}T00:00:00`)-new Date(`${gameState.date}T00:00:00`))/86400000))} DAYS · ${c.endDate}</span></div>`:''}<button class="primary full" data-build="${type}" ${(!d.next||c)?'disabled':''}>${!d.f.owned?'BUY LAND + BUILD':'UPGRADE'}${d.next?` → ${money(d.next.cost)}`:''}</button></article>`}).join('')}</div>`;host.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>build(b.dataset.build));}
  function build(type){const d=levelData(type);if(!d.next||d.f.construction)return;if(gameState.money<d.next.cost){alert(`Not enough funds. Required: ${money(d.next.cost)}`);return}gameState.money-=d.next.cost;d.f.owned=true;d.f.construction={targetLevel:d.f.level+1,endDate:addDays(gameState.date,d.next.days)};persist();syncDashboard();render()}
  function complete(){const f=ensure();Object.keys(TYPES).forEach(type=>{const x=f[type];if(x.construction&&gameState.date>=x.construction.endDate){x.level=x.construction.targetLevel;x.construction=null;x.owned=true}})}
  function mount(){if(!document.getElementById('dashboard'))return;let host=document.getElementById('clubFacilities');if(!host){host=document.createElement('section');host.id='clubFacilities';host.className='club-facilities';const stadium=document.getElementById('stadiumDevelopment');(stadium||document.querySelector('.dashboard-panels'))?.insertAdjacentElement('afterend',host)}complete();render()}
  window.addEventListener('load',mount);window.addEventListener('nexora:career-ready',mount);window.NEXORA_FACILITIES={render,complete};
})();