(() => {
  const TYPES={
    training:{name:'ANTRENMAN TESİSİ',key:'training',levels:[{name:'EMPTY LAND',cost:150000,days:14,effect:'Temel antrenman alanı'},{name:'TRAINING GROUND',cost:450000,days:30,effect:'+2 gelişim / hafta'},{name:'PRO TRAINING CENTRE',cost:1200000,days:60,effect:'+4 gelişim / hafta'},{name:'ELITE TRAINING CAMPUS',cost:3000000,days:90,effect:'+7 gelişim / hafta'}]},
    medical:{name:'SAĞLIK MERKEZİ',key:'medical',levels:[{name:'EMPTY LAND',cost:100000,days:10,effect:'Temel sağlık odası'},{name:'CLUB CLINIC',cost:350000,days:25,effect:'Toparlanma hızlanır'},{name:'MEDICAL CENTRE',cost:900000,days:45,effect:'Sakatlık süresi -20%'},{name:'ELITE MEDICAL CAMPUS',cost:2000000,days:70,effect:'Sakatlık süresi -35%'}]},
    academy:{name:'GENÇ AKADEMİSİ',key:'academy',levels:[{name:'EMPTY LAND',cost:250000,days:18,effect:'Altyapı izleme başlar'},{name:'YOUTH ACADEMY',cost:700000,days:45,effect:'Her sezon genç aday üretir'},{name:'ELITE YOUTH ACADEMY',cost:1800000,days:75,effect:'Daha yüksek potansiyel'},{name:'NEXORA YOUTH CAMPUS',cost:4000000,days:110,effect:'Nadir yıldız adayları + güçlü gelir'}]}
  };
  const money=v=>`€${(v/1000000).toFixed(1)}M`;
  const addDays=(date,days)=>{const d=new Date(`${date}T00:00:00`);d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};
  const ensure=()=>{if(!gameState.facilities)gameState.facilities={training:{level:0,owned:false,construction:null},medical:{level:0,owned:false,construction:null},academy:{level:0,owned:false,construction:null,lastIntake:null,prospects:[],signed:[]}};if(!gameState.facilities.academy)gameState.facilities.academy={level:0,owned:false,construction:null,lastIntake:null,prospects:[],signed:[]};gameState.facilities.academy.signed ||= [];return gameState.facilities};
  const levelData=type=>{const f=ensure()[type],list=TYPES[type].levels;return {f,list,current:list[f.level]||list[0],next:list[f.level+1]}};
  const academyNames=['Arda Yılmaz','Mert Kaya','Efe Demir','Emir Can','Bora Aydın','Kerem Şahin','Yiğit Arslan','Can Eren','Kaan Özdemir'];
  function generateYouth(){const f=ensure().academy;if(!f.owned||f.level<1)return null;if(f.lastIntake===gameState.date)return null;const count=f.level>=3?3:f.level>=2?2:1;const prospects=[];for(let i=0;i<count;i++){const potential=Math.min(92,58+f.level*7+Math.floor(Math.random()*18));const rating=46+Math.floor(Math.random()*12)+f.level*2;const positions=['ST','AM','CM','CB','LB','RB','GK'];const name=academyNames[Math.floor(Math.random()*academyNames.length)];prospects.push({id:`youth-${Date.now()}-${i}`,name:`${name} ${String.fromCharCode(65+i)}`,age:15+Math.floor(Math.random()*3),pos:positions[Math.floor(Math.random()*positions.length)],rating,potential,value:Math.max(50000,potential*18000),homegrown:true});}f.prospects=prospects;f.lastIntake=gameState.date;persist();return prospects}
  function signYouth(index){const f=ensure().academy,p=f.prospects[index];if(!p)return;f.signed.push({...p,contract:'academy'});f.prospects.splice(index,1);persist();render();alert(`${p.name} akademi kadrosuna alındı.`)}
  function academyHTML(){const f=ensure().academy;if(f.owned&&f.level>0&&!f.prospects.length)generateYouth();return `<div class="academy-panel"><div class="academy-visual"><div class="academy-pitch"></div><div class="academy-building">YOUTH<br>CAMPUS</div><div class="academy-scout">SCOUTING<br>NETWORK</div></div><div class="academy-info"><span class="eyebrow">YOUTH DEVELOPMENT</span><h4>Genç Akademisi</h4><p>Buradan geleceğin yıldızlarını çıkar. Oyuncuyu geliştir, A takıma yükselt veya ileride satıştan gelir elde et.</p><div class="academy-stats"><div><b>${f.level}</b><span>ACADEMY LVL</span></div><div><b>${f.prospects.length}</b><span>NEW PROSPECTS</span></div><div><b>${f.signed.length}</b><span>ACADEMY PLAYERS</span></div></div>${f.prospects.length?`<div class="prospect-list">${f.prospects.map((p,i)=>`<div class="prospect"><div><strong>${p.name}</strong><span>${p.age} YAŞ · ${p.pos} · OVR ${p.rating}</span></div><b>POT ${p.potential}</b><button data-sign-youth="${i}">KADROYA AL</button></div>`).join('')}</div>`:'<div class="academy-empty">Yeni nesil adaylar burada görünecek.</div>'}${f.signed.length?`<div class="academy-signed"><span class="eyebrow">SIGNED YOUTH</span><p>${f.signed.map(p=>`${p.name} · ${p.pos} · POT ${p.potential}`).join(' &nbsp; / &nbsp; ')}</p><small>A takıma yükseltme Transfer & Scouting merkezinden yapılır.</small></div>`:''}</div></div>`}
  function render(){const host=document.getElementById('clubFacilities');if(!host)return;const f=ensure();host.innerHTML=`<div class="facility-head"><div><span class="eyebrow">CLUB DEVELOPMENT / INFRASTRUCTURE</span><h3>Build the football machine.</h3><p>Arsa al, tesis kur, zaman geçir ve kulübün değerini büyüt. Altyapı artık sadece masraf değil, gelecekteki gelir kaynağın.</p></div><span class="eyebrow">LAND + CONSTRUCTION + YOUTH</span></div><div class="facility-grid">${['training','academy','medical'].map(type=>{const d=levelData(type),c=d.f.construction;return `<article class="facility-card"><div class="facility-icon">${type==='training'?'TR':type==='academy'?'YA':'MD'}</div><span class="eyebrow">${TYPES[type].name}</span><h4>${d.current.name}</h4><p>${d.current.effect}</p><div class="facility-stat"><span>STATUS</span><b>${c?'IN CONSTRUCTION':d.f.owned?'ACTIVE':'NO LAND'}</b></div><div class="facility-stat"><span>LEVEL</span><b>${d.f.level}/${d.list.length-1}</b></div>${c?`<div class="facility-build"><strong>BUILDING</strong><span>${Math.max(0,Math.ceil((new Date(`${c.endDate}T00:00:00`)-new Date(`${gameState.date}T00:00:00`))/86400000))} DAYS · ${c.endDate}</span></div>`:''}<button class="primary full" data-build="${type}" ${(!d.next||c)?'disabled':''}>${!d.f.owned?'BUY LAND + BUILD':'UPGRADE'}${d.next?` → ${money(d.next.cost)}`:''}</button></article>`}).join('')}</div>${f.academy.owned?academyHTML():''}`;host.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>build(b.dataset.build));host.querySelectorAll('[data-sign-youth]').forEach(b=>b.onclick=()=>signYouth(Number(b.dataset.signYouth)));}
  function build(type){const d=levelData(type);if(!d.next||d.f.construction)return;if(gameState.money<d.next.cost){alert(`Not enough funds. Required: ${money(d.next.cost)}`);return}gameState.money-=d.next.cost;d.f.owned=true;d.f.construction={targetLevel:d.f.level+1,endDate:addDays(gameState.date,d.next.days)};persist();syncDashboard();render()}
  function complete(){const f=ensure();Object.keys(TYPES).forEach(type=>{const x=f[type];if(x.construction&&gameState.date>=x.construction.endDate){x.level=x.construction.targetLevel;x.construction=null;x.owned=true;if(type==='academy')generateYouth()}})}
  function mount(){if(!document.getElementById('dashboard'))return;let host=document.getElementById('clubFacilities');if(!host){host=document.createElement('section');host.id='clubFacilities';host.className='club-facilities';const stadium=document.getElementById('stadiumDevelopment');(stadium||document.querySelector('.dashboard-panels'))?.insertAdjacentElement('afterend',host)}complete();render()}
  window.addEventListener('load',mount);window.addEventListener('nexora:career-ready',mount);window.NEXORA_FACILITIES={render,complete,generateYouth};
})();