(()=>{
const KEY='nexoraCareer';
const get=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const put=s=>{localStorage.setItem(KEY,JSON.stringify(s));localStorage.setItem('nexoraGameState',JSON.stringify(s.gameState))};
const money=n=>`€${Math.round(n||0).toLocaleString('tr-TR')}`;
function fixture(s,id){return s.gameState.fixtures?.rounds?.flatMap(r=>r.games.map(g=>({...g,round:r.round,date:r.date}))).find(g=>g.id===id)}
function team(s,id){return s.gameState.fixtures.teams.find(t=>t.id===id)}
function score(s,g){const seed=(g.home.length*13+g.away.length*7+g.round*11)%17;let hg=Math.max(0,Math.min(5,Math.floor(Math.random()*3)+(seed%3===0?1:0)));let ag=Math.max(0,Math.min(4,Math.floor(Math.random()*3)+(seed%5===0?1:0)));if(g.home===s.gameState.club.id)hg=Math.max(hg,0);return[hg,ag]}
function rebuild(s){const f=s.gameState.fixtures,rows=f.teams.map(t=>({clubId:t.id,name:t.name,code:t.code,played:0,wins:0,draws:0,losses:0,gf:0,ga:0,gd:0,points:0})),by=Object.fromEntries(rows.map(x=>[x.clubId,x]));for(const r of f.rounds)for(const g of r.games)if(g.status==='played'){const h=by[g.home],a=by[g.away],hg=+g.homeGoals||0,ag=+g.awayGoals||0;if(!h||!a)continue;h.played++;a.played++;h.gf+=hg;h.ga+=ag;a.gf+=ag;a.ga+=hg;h.gd=h.gf-h.ga;a.gd=a.gf-a.ga;if(hg>ag){h.wins++;a.losses++;h.points+=3}else if(hg===ag){h.draws++;a.draws++;h.points++;a.points++}else{h.losses++;a.wins++;a.points+=3}}rows.sort((a,b)=>b.points-a.points||b.gd-a.gd||b.gf-a.gf||a.name.localeCompare(b.name,'tr'));s.gameState.standings=rows;s.gameState.leaguePosition=(rows.findIndex(x=>x.clubId===s.gameState.club.id)+1)||0;s.gameState.matchHistory=f.rounds.flatMap(r=>r.games.filter(g=>g.status==='played').map(g=>({id:g.id,date:r.date,home:team(s,g.home).name,away:team(s,g.away).name,homeGoals:g.homeGoals,awayGoals:g.awayGoals,points:g.home===s.gameState.club.id?(g.homeGoals>g.awayGoals?3:g.homeGoals===g.awayGoals?1:0):g.away===s.gameState.club.id?(g.awayGoals>g.homeGoals?3:g.awayGoals===g.homeGoals?1:0):0}))).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,30);put(s);window.dispatchEvent(new CustomEvent('nexora:standings-updated',{detail:{table:rows,position:s.gameState.leaguePosition}}))}
function process(detail){const s=get();if(!s?.gameState?.club||!s.gameState.fixtures)return;const n=s.gameState.nextFixture,g=fixture(s,detail.matchId||n?.id);if(!g||g.status==='played')return;g.status='played';g.homeGoals=Number(detail.homeGoals)||0;g.awayGoals=Number(detail.awayGoals)||0;const r=s.gameState.fixtures.rounds.find(x=>x.round===g.round);if(r)for(const x of r.games)if(x.status==='scheduled'){const [hg,ag]=score(s,x);x.status='played';x.homeGoals=hg;x.awayGoals=ag}if(r)r.played=true;s.gameState.fixtures.lastProcessed=g.id;rebuild(s);window.NEXORA_FIXTURES?.syncNext?.(s);put(s);window.NEXORA_FIXTURES?.render?.(s);window.NEXORA_MEDIA?.render?.();if(window.NEXORA_CAREER_LOOP?.news)window.NEXORA_CAREER_LOOP.news(s,'MATCHWEEK TAMAMLANDI','LEAGUE',`${g.round}. hafta tamamlandı. Lig sırası: ${s.gameState.leaguePosition}. Bütçe: ${money(s.gameState.money)}.`)}
function style(){if(document.getElementById('fixtureStyle'))return;const st=document.createElement('style');st.id='fixtureStyle';st.textContent='.fixture-center{margin:22px 0;padding:24px;border:1px solid rgba(130,255,180,.16);background:linear-gradient(145deg,rgba(8,14,12,.98),rgba(14,20,18,.92));border-radius:18px;color:#e8fff2}.fixture-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.fixture-head h3{margin:5px 0}.fixture-head p{opacity:.65}.fixture-next{margin:18px 0;padding:20px;border:1px solid rgba(130,255,180,.12);display:flex;align-items:center;justify-content:center;gap:20px;flex-wrap:wrap}.fixture-next strong{font-size:20px}.fixture-next b{font-size:24px}.fixture-next span,.fixture-next small{opacity:.65}.fixture-weeks{display:grid;grid-template-columns:repeat(17,1fr);gap:6px}.fixture-week{padding:8px 4px;text-align:center;border:1px solid rgba(255,255,255,.08);border-radius:8px;font-size:12px;opacity:.65}.fixture-week small{display:block;margin-top:3px;font-size:9px}.fixture-week.played{opacity:1;border-color:rgba(130,255,180,.25)}.fixture-week.next{box-shadow:0 0 0 1px rgba(183,255,60,.65) inset;opacity:1}.fixture-status{font-size:11px;letter-spacing:.12em}.fixture-status.ready{color:#b7ff3c}@media(max-width:800px){.fixture-weeks{grid-template-columns:repeat(9,1fr)}.fixture-next{gap:10px}.fixture-next strong{font-size:16px}}';document.head.appendChild(st)}
style();window.addEventListener('nexora:match-event',e=>{if(e.detail?.type==='fulltime')setTimeout(()=>process(e.detail),50)});window.NEXORA_FIXTURES_PROCESS=process;
})();