(()=>{
const KEY='nexoraCareer';
const AI=[['Karadeniz FK','KRD'],['Başkent 1910','BSK'],['Akdeniz Birliği','AKD'],['Kapadokya Spor','KPD'],['Doğu Yıldızları','DYS'],['Marmara 1907','MMR'],['Çukurova FK','CUK'],['Batı Anadolu','BTA'],['Karadeniz 1967','K67'],['İç Anadolu SK','IAS'],['Akdeniz 07','A07'],['Ege Birlik','EGB'],['Boğaziçi FK','BGZ'],['Doğu Anadolu 1968','DA8']];
const get=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const put=s=>{localStorage.setItem(KEY,JSON.stringify(s));localStorage.setItem('nexoraGameState',JSON.stringify(s.gameState))};
const addDay=(d,n)=>{const x=new Date(d+'T00:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)};
function makeTeams(s){const real=(window.NEXORA_DATA?.clubs||[]).map(c=>({id:c.id,name:c.name,code:c.code,city:c.city}));return real.concat(AI.map((x,i)=>({id:'ai-'+i,name:x[0],code:x[1],city:'Türkiye'})))}
function schedule(list){const fixed=list[0],rest=list.slice(1),rounds=[];for(let r=0;r<rest.length;r++){const arr=[fixed,...rest],games=[];for(let i=0;i<arr.length/2;i++){let h=arr[i],a=arr[arr.length-1-i];if(r%2)[h,a]=[a,h];games.push({home:h.id,away:a.id})}rounds.push(games);rest.splice(1,0,rest.pop())}const second=rounds.map((games)=>games.map(g=>({home:g.away,away:g.home})));return rounds.concat(second)}
function ensure(s){if(!s?.gameState?.club)return null;const season=s.gameState.season||'2026/27';if(s.gameState.fixtures?.season===season)return s.gameState.fixtures;const teams=makeTeams(s),start='2026-08-15',first=schedule(teams);s.gameState.fixtures={season,teams,rounds:first.map((games,i)=>({round:i+1,date:addDay(start,i*7),games:games.map((g,j)=>({id:`${season}-${i+1}-${j+1}`,home:g.home,away:g.away,status:'scheduled',homeGoals:null,awayGoals:null}))})),lastProcessed:null};syncNext(s);put(s);return s.gameState.fixtures}
function syncNext(s){const f=s.gameState.fixtures,c=s.gameState.club?.id;if(!f||!c)return;let n=null;for(const r of f.rounds){const g=r.games.find(x=>(x.home===c||x.away===c)&&x.status!=='played');if(g){const hn=f.teams.find(t=>t.id===g.home),an=f.teams.find(t=>t.id===g.away);n={...g,round:r.round,date:r.date,homeName:hn?.name,awayName:an?.name,homeTeam:g.home===c,daysUntil:Math.max(0,Math.ceil((new Date(r.date)-new Date(s.gameState.date))/86400000))};break}}s.gameState.nextFixture=n||null}
function render(s){const h=document.getElementById('fixtureCenter'),f=s?.gameState?.fixtures,n=s?.gameState?.nextFixture;if(!h||!f)return;h.innerHTML=`<div class="fixture-head"><div><span class="eyebrow">SEASON ENGINE / FIXTURE DESK</span><h3>${s.gameState.season||'2026/27'} LİG FİKSTÜRÜ</h3><p>34 hafta · 18 takım · çift devreli lig</p></div><b>WEEK ${n?.round||34} / 34</b></div><div class="fixture-next">${n?`<strong>${n.homeName}</strong><span>${n.homeTeam?'EV':'DEP'}</span><b>VS</b><strong>${n.awayName}</strong><small>${n.date} · ${n.daysUntil?`BAŞLAMASINA ${n.daysUntil} GÜN`:'MATCHDAY'}</small>`:'SEZON TAMAMLANDI'}</div><div class="fixture-weeks">${f.rounds.map(r=>{const g=r.games.find(x=>x.home===s.gameState.club.id||x.away===s.gameState.club.id);return `<span class="fixture-week ${g?.status==='played'?'played':''} ${r.date===n?.date?'next':''}">${r.round}<small>${r.date.slice(5)}</small></span>`}).join('')}</div>`}
function mount(){const d=document.getElementById('dashboard');if(!d)return;let h=document.getElementById('fixtureCenter');if(!h){h=document.createElement('section');h.id='fixtureCenter';h.className='fixture-center';(document.querySelector('.dashboard-panels')||d).insertAdjacentElement('afterend',h)}const s=get();if(s?.gameState?.club){ensure(s);syncNext(s);put(s);render(s)}}
window.NEXORA_FIXTURES={ensure,syncNext,render,getNext:()=>get()?.gameState?.nextFixture};
window.addEventListener('load',mount);window.addEventListener('nexora:career-ready',mount);window.addEventListener('nexora:day-advanced',()=>{const s=get();if(s?.gameState?.club){ensure(s);syncNext(s);put(s);render(s)}});
})();