(()=>{
const LANGS={
 tr:{name:'Türkçe',locale:'tr-TR',currency:'EUR',symbol:'€',pos:{GK:'Kaleci',CB:'Stoper',RB:'Sağ Bek',LB:'Sol Bek',DM:'Ön Libero',CM:'Merkez Orta Saha',AM:'Ofansif Orta Saha',RW:'Sağ Kanat',LW:'Sol Kanat',ST:'Santrafor'},ui:{dashboard:'KONTROL MERKEZİ',squad:'KADRO',firstTeam:'A TAKIM',tactics:'TAKTİKLER',transfer:'TRANSFER & SCOUTING',news:'FUTBOL GÜNDEMİ',nextDay:'SONRAKİ GÜNE İLERLE',continue:'DEVAM ET',live:'CANLI',startMatch:'MAÇI BAŞLAT',prepare:'MAÇA HAZIRLAN',formation:'FORMASYON',manager:'MENAJER',opponent:'RAKİP',budget:'BÜTÇE',wage:'MAAŞ',value:'DEĞER',academy:'ALTYAPI',language:'DİL',currency:'PARA BİRİMİ'},news:{big:'{player} için flaş transfer: {club} yıldızını kadrosuna kattı',future:'{player}: Geleceğin yıldızı {club} ile imzaladı',normal:'{player} yeni takımına katıldı'}},
 en:{name:'English',locale:'en-GB',currency:'EUR',symbol:'€',pos:{GK:'Goalkeeper',CB:'Centre Back',RB:'Right Back',LB:'Left Back',DM:'Defensive Midfielder',CM:'Central Midfielder',AM:'Attacking Midfielder',RW:'Right Wing',LW:'Left Wing',ST:'Striker'},ui:{dashboard:'CONTROL CENTER',squad:'SQUAD',firstTeam:'FIRST TEAM',tactics:'TACTICS',transfer:'TRANSFER & SCOUTING',news:'FOOTBALL NEWS',nextDay:'ADVANCE TO NEXT DAY',continue:'CONTINUE',live:'LIVE',startMatch:'START MATCH',prepare:'PREPARE MATCH',formation:'FORMATION',manager:'MANAGER',opponent:'OPPONENT',budget:'BUDGET',wage:'WAGE',value:'VALUE',academy:'ACADEMY',language:'LANGUAGE',currency:'CURRENCY'},news:{big:'Breaking transfer: {club} sign star {player}',future:'{player}: Future star signs for {club}',normal:'{player} joins a new club'}},
 de:{name:'Deutsch',locale:'de-DE',currency:'EUR',symbol:'€',pos:{GK:'Torwart',CB:'Innenverteidiger',RB:'Rechter Verteidiger',LB:'Linker Verteidiger',DM:'Defensives Mittelfeld',CM:'Zentrales Mittelfeld',AM:'Offensives Mittelfeld',RW:'Rechtsaußen',LW:'Linksaußen',ST:'Stürmer'},ui:{dashboard:'KONTROLLZENTRUM',squad:'KADER',firstTeam:'ERSTE MANNSCHAFT',tactics:'TAKTIK',transfer:'TRANSFER & SCOUTING',news:'FUSSBALL-NACHRICHTEN',nextDay:'ZUM NÄCHSTEN TAG',continue:'WEITER',live:'LIVE',startMatch:'SPIEL STARTEN',prepare:'SPIEL VORBEREITEN',formation:'FORMATION',manager:'TRAINER',opponent:'GEGNER',budget:'BUDGET',wage:'GEHALT',value:'WERT',academy:'JUGEND',language:'SPRACHE',currency:'WÄHRUNG'},news:{big:'Transfer-Hammer: {club} verpflichtet Star {player}',future:'{player}: Zukunftstalent unterschreibt bei {club}',normal:'{player} wechselt zu einem neuen Klub'}},
 es:{name:'Español',locale:'es-ES',currency:'EUR',symbol:'€',pos:{GK:'Portero',CB:'Defensa central',RB:'Lateral derecho',LB:'Lateral izquierdo',DM:'Mediocentro defensivo',CM:'Centrocampista',AM:'Mediapunta',RW:'Extremo derecho',LW:'Extremo izquierdo',ST:'Delantero'},ui:{dashboard:'CENTRO DE CONTROL',squad:'PLANTILLA',firstTeam:'PRIMER EQUIPO',tactics:'TÁCTICA',transfer:'TRANSFERENCIAS Y SCOUTING',news:'NOTICIAS DE FÚTBOL',nextDay:'AVANZAR AL SIGUIENTE DÍA',continue:'CONTINUAR',live:'EN DIRECTO',startMatch:'EMPEZAR PARTIDO',prepare:'PREPARAR PARTIDO',formation:'FORMACIÓN',manager:'ENTRENADOR',opponent:'RIVAL',budget:'PRESUPUESTO',wage:'SALARIO',value:'VALOR',academy:'CANTERA',language:'IDIOMA',currency:'MONEDA'},news:{big:'Fichaje bomba: {club} incorpora a la estrella {player}',future:'{player}: la futura estrella firma por {club}',normal:'{player} se une a un nuevo club'}},
 pt:{name:'Português',locale:'pt-BR',currency:'EUR',symbol:'€',pos:{GK:'Goleiro',CB:'Zagueiro',RB:'Lateral direito',LB:'Lateral esquerdo',DM:'Volante',CM:'Meio-campista',AM:'Meia ofensivo',RW:'Ponta direita',LW:'Ponta esquerda',ST:'Atacante'},ui:{dashboard:'CENTRAL DE CONTROLE',squad:'ELENCO',firstTeam:'TIME PRINCIPAL',tactics:'TÁTICAS',transfer:'TRANSFERÊNCIAS E SCOUTING',news:'NOTÍCIAS DO FUTEBOL',nextDay:'AVANÇAR PARA O PRÓXIMO DIA',continue:'CONTINUAR',live:'AO VIVO',startMatch:'INICIAR PARTIDA',prepare:'PREPARAR PARTIDA',formation:'FORMAÇÃO',manager:'TREINADOR',opponent:'ADVERSÁRIO',budget:'ORÇAMENTO',wage:'SALÁRIO',value:'VALOR',academy:'BASE',language:'IDIOMA',currency:'MOEDA'},news:{big:'Grande contratação: {club} anuncia a estrela {player}',future:'{player}: jovem promessa assina com {club}',normal:'{player} chega a um novo clube'}}
};
const KEY='nexoraLanguage';
let current=localStorage.getItem(KEY)||'tr';if(!LANGS[current])current='tr';
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function lang(){return LANGS[current]}
function t(path,vars={}){let v=path.split('.').reduce((o,k)=>o?.[k],lang())??path;return Object.keys(vars).reduce((x,k)=>x.replaceAll(`{${k}}`,vars[k]),v)}
function position(pos){return lang().pos[pos]||pos}
function money(value){return new Intl.NumberFormat(lang().locale,{style:'currency',currency:lang().currency,maximumFractionDigits:0}).format(Number(value)||0)}
function date(value){if(!value)return '—';return new Intl.DateTimeFormat(lang().locale,{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${value}T00:00:00`)).toUpperCase()}
function renderPicker(){let host=document.getElementById('languagePicker');if(!host){host=document.createElement('div');host.id='languagePicker';host.className='language-picker';(document.getElementById('dashboard')||document.body).prepend(host)}host.innerHTML=`<label><span>◉ ${esc(t('ui.language'))}</span><select id="nexoraLanguageSelect">${Object.entries(LANGS).map(([k,v])=>`<option value="${k}" ${k===current?'selected':''}>${v.name}</option>`).join('')}</select></label>`;host.querySelector('select').onchange=e=>setLanguage(e.target.value)}
function translateNode(root=document.body){const replacements={
'DASHBOARD':t('ui.dashboard'),'SQUAD':t('ui.squad'),'FIRST TEAM':t('ui.firstTeam'),'YOUR GAME PLAN':t('ui.tactics'),'TACTICS':t('ui.tactics'),'TRANSFER & SCOUTING':t('ui.transfer'),'FUTBOL GÜNDEMİ':t('ui.news'),'FOOTBALL NEWS':t('ui.news'),'CONTINUE →':t('ui.continue)+' →','START MATCH →':t('ui.startMatch)+' →','PREPARE MATCH →':t('ui.prepare')+' →','FORMATION':t('ui.formation'),'MANAGER':t('ui.manager'),'OPPONENT':t('ui.opponent'),'BUDGET':t('ui.budget'),'WAGE':t('ui.wage'),'VALUE':t('ui.value'),'ACADEMY':t('ui.academy'),'LIVE':t('ui.live'),'DİL':t('ui.language')};
const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{if(!n.nodeValue.trim())return;let v=n.nodeValue.trim();if(replacements[v]&&n.parentElement?.children.length===0)n.nodeValue=n.nodeValue.replace(v,replacements[v]);const m=v.match(/^(GK|CB|RB|LB|DM|CM|AM|RW|LW|ST)$/);if(m)n.nodeValue=n.nodeValue.replace(m[1],position(m[1]));});renderPicker()}
function setLanguage(next){if(!LANGS[next])return;current=next;localStorage.setItem(KEY,next);document.documentElement.lang=next;document.documentElement.dataset.language=next;translateNode();window.dispatchEvent(new CustomEvent('nexora:language-changed',{detail:{language:next}}));}
window.NEXORA_I18N={languages:LANGS,get language(){return current},t,position,money,date,setLanguage,refresh:translateNode};
window.addEventListener('load',()=>{document.documentElement.lang=current;translateNode();});window.addEventListener('nexora:career-ready',()=>setTimeout(translateNode,50));window.addEventListener('nexora:transfer-updated',()=>setTimeout(translateNode,50));window.addEventListener('nexora:day-advanced',()=>setTimeout(translateNode,50));
})();