/* NEXORA FOOTBALL MANAGER — INTERNATIONAL CLUB DATABASE */
(function(){
 const clubs=[
  // ENGLAND — PREMIER LEAGUE
  {id:'eng-ars',name:'Arsenal',city:'London',code:'ARS',style:'Technical',league:'Premier League',leagueCountry:'gb',difficulty:'HARD',budget:180000000,reputation:88,stadiumCapacity:60704,colors:['#ef0107','#ffffff']},
  {id:'eng-avl',name:'Aston Villa',city:'Birmingham',code:'AVL',style:'Balanced',league:'Premier League',leagueCountry:'gb',difficulty:'HARD',budget:90000000,reputation:78,stadiumCapacity:42657,colors:['#670e36','#94bee5']},
  {id:'eng-bou',name:'AFC Bournemouth',city:'Bournemouth',code:'BOU',style:'Attacking',league:'Premier League',leagueCountry:'gb',difficulty:'NORMAL',budget:45000000,reputation:68,stadiumCapacity:11307,colors:['#da291c','#000000']},
  {id:'eng-bre',name:'Brentford',city:'London',code:'BRE',style:'Balanced',league:'Premier League',leagueCountry:'gb',difficulty:'NORMAL',budget:50000000,reputation:70,stadiumCapacity:17250,colors:['#e30613','#ffffff']},
  {id:'eng-bha',name:'Brighton & Hove Albion',city:'Brighton',code:'BHA',style:'Technical',league:'Premier League',leagueCountry:'gb',difficulty:'NORMAL',budget:65000000,reputation:75,stadiumCapacity:31872,colors:['#0057b8','#ffffff']},
  {id:'eng-bur',name:'Burnley',city:'Burnley',code:'BUR',style:'Defensive',league:'Premier League',leagueCountry:'gb',difficulty:'CHALLENGE',budget:35000000,reputation:65,stadiumCapacity:22546,colors:['#6c1d45','#87ceeb']},
  {id:'eng-che',name:'Chelsea',city:'London',code:'CHE',style:'Attacking',league:'Premier League',leagueCountry:'gb',difficulty:'HARD',budget:220000000,reputation:90,stadiumCapacity:40341,colors:['#034694','#ffffff']},
  {id:'eng-cry',name:'Crystal Palace',city:'London',code:'CRY',style:'Attacking',league:'Premier League',leagueCountry:'gb',difficulty:'NORMAL',budget:55000000,reputation:72,stadiumCapacity:26309,colors:['#1b458f','#c4122e']},
  {id:'eng-eve',name:'Everton',city:'Liverpool',code:'EVE',style:'Balanced',league:'Premier League',leagueCountry:'gb',difficulty:'NORMAL',budget:60000000,reputation:76,stadiumCapacity:52888,colors:['#003399','#ffffff']},
  {id:'eng-ful',name:'Fulham',city:'London',code:'FUL',style:'Technical',league:'Premier League',leagueCountry:'gb',difficulty:'NORMAL',budget:50000000,reputation:71,stadiumCapacity:29589,colors:['#000000','#ffffff']},
  {id:'eng-lee',name:'Leeds United',city:'Leeds',code:'LEE',style:'Attacking',league:'Premier League',leagueCountry:'gb',difficulty:'NORMAL',budget:70000000,reputation:77,stadiumCapacity:40204,colors:['#ffcd00','#1d428a']},
  {id:'eng-liv',name:'Liverpool',city:'Liverpool',code:'LIV',style:'Attacking',league:'Premier League',leagueCountry:'gb',difficulty:'HARD',budget:210000000,reputation:94,stadiumCapacity:61276,colors:['#c8102e','#00b2a9']},
  {id:'eng-mci',name:'Manchester City',city:'Manchester',code:'MCI',style:'Technical',league:'Premier League',leagueCountry:'gb',difficulty:'HARD',budget:250000000,reputation:96,stadiumCapacity:53400,colors:['#6cabdd','#ffffff']},
  {id:'eng-mun',name:'Manchester United',city:'Manchester',code:'MUN',style:'Attacking',league:'Premier League',leagueCountry:'gb',difficulty:'HARD',budget:200000000,reputation:93,stadiumCapacity:76212,colors:['#da291c','#fbe122']},
  {id:'eng-new',name:'Newcastle United',city:'Newcastle',code:'NEW',style:'Balanced',league:'Premier League',leagueCountry:'gb',difficulty:'HARD',budget:150000000,reputation:84,stadiumCapacity:52758,colors:['#241f20','#ffffff']},
  {id:'eng-not',name:'Nottingham Forest',city:'Nottingham',code:'NFO',style:'Defensive',league:'Premier League',leagueCountry:'gb',difficulty:'NORMAL',budget:60000000,reputation:73,stadiumCapacity:30576,colors:['#e53233','#ffffff']},
  {id:'eng-sun',name:'Sunderland',city:'Sunderland',code:'SUN',style:'Balanced',league:'Premier League',leagueCountry:'gb',difficulty:'CHALLENGE',budget:40000000,reputation:68,stadiumCapacity:49000,colors:['#eb172b','#ffffff']},
  {id:'eng-tot',name:'Tottenham Hotspur',city:'London',code:'TOT',style:'Attacking',league:'Premier League',leagueCountry:'gb',difficulty:'HARD',budget:170000000,reputation:87,stadiumCapacity:62850,colors:['#132257','#ffffff']},
  {id:'eng-whu',name:'West Ham United',city:'London',code:'WHU',style:'Balanced',league:'Premier League',leagueCountry:'gb',difficulty:'NORMAL',budget:80000000,reputation:79,stadiumCapacity:64472,colors:['#7a263a','#1bb1e7']},
  {id:'eng-wol',name:'Wolverhampton Wanderers',city:'Wolverhampton',code:'WOL',style:'Defensive',league:'Premier League',leagueCountry:'gb',difficulty:'NORMAL',budget:55000000,reputation:74,stadiumCapacity:34624,colors:['#fdb913','#231f20']},
  // SPAIN — LA LIGA
  {id:'esp-ala',name:'Alavés',city:'Vitoria-Gasteiz',code:'ALA',style:'Defensive',league:'La Liga',leagueCountry:'es',difficulty:'CHALLENGE',budget:30000000,reputation:68,stadiumCapacity:19840,colors:['#0067b1','#ffffff']},
  {id:'esp-ath',name:'Athletic Club',city:'Bilbao',code:'ATH',style:'Balanced',league:'La Liga',leagueCountry:'es',difficulty:'HARD',budget:80000000,reputation:84,stadiumCapacity:53289,colors:['#ee2523','#ffffff']},
  {id:'esp-atm',name:'Atlético Madrid',city:'Madrid',code:'ATM',style:'Defensive',league:'La Liga',leagueCountry:'es',difficulty:'HARD',budget:140000000,reputation:91,stadiumCapacity:70460,colors:['#ce3529','#ffffff']},
  {id:'esp-bar',name:'Barcelona',city:'Barcelona',code:'BAR',style:'Technical',league:'La Liga',leagueCountry:'es',difficulty:'HARD',budget:220000000,reputation:96,stadiumCapacity:99354,colors:['#a50044','#004d98']},
  {id:'esp-cel',name:'Celta Vigo',city:'Vigo',code:'CEL',style:'Technical',league:'La Liga',leagueCountry:'es',difficulty:'NORMAL',budget:45000000,reputation:74,stadiumCapacity:29000,colors:['#8ac6e8','#ffffff']},
  {id:'esp-esp',name:'Espanyol',city:'Barcelona',code:'ESP',style:'Balanced',league:'La Liga',leagueCountry:'es',difficulty:'NORMAL',budget:45000000,reputation:73,stadiumCapacity:40242,colors:['#007fc8','#ffffff']},
  {id:'esp-get',name:'Getafe',city:'Getafe',code:'GET',style:'Defensive',league:'La Liga',leagueCountry:'es',difficulty:'NORMAL',budget:35000000,reputation:70,stadiumCapacity:17393,colors:['#005999','#ffffff']},
  {id:'esp-gir',name:'Girona',city:'Girona',code:'GIR',style:'Technical',league:'La Liga',leagueCountry:'es',difficulty:'NORMAL',budget:65000000,reputation:78,stadiumCapacity:14624,colors:['#cd2b3e','#ffffff']},
  {id:'esp-las',name:'Las Palmas',city:'Las Palmas',code:'LPA',style:'Technical',league:'La Liga',leagueCountry:'es',difficulty:'CHALLENGE',budget:30000000,reputation:67,stadiumCapacity:32392,colors:['#ffcc00','#0072bc']},
  {id:'esp-lev',name:'Levante',city:'Valencia',code:'LEV',style:'Attacking',league:'La Liga',leagueCountry:'es',difficulty:'CHALLENGE',budget:30000000,reputation:67,stadiumCapacity:26354,colors:['#1e5aa8','#d50032']},
  {id:'esp-mal',name:'Mallorca',city:'Palma',code:'MLL',style:'Defensive',league:'La Liga',leagueCountry:'es',difficulty:'NORMAL',budget:35000000,reputation:71,stadiumCapacity:23142,colors:['#e30613','#000000']},
  {id:'esp-osa',name:'Osasuna',city:'Pamplona',code:'OSA',style:'Balanced',league:'La Liga',leagueCountry:'es',difficulty:'NORMAL',budget:40000000,reputation:72,stadiumCapacity:23576,colors:['#d91a2a','#002e5d']},
  {id:'esp-rayo',name:'Rayo Vallecano',city:'Madrid',code:'RAY',style:'Attacking',league:'La Liga',leagueCountry:'es',difficulty:'NORMAL',budget:35000000,reputation:70,stadiumCapacity:14708,colors:['#e30613','#ffffff']},
  {id:'esp-rma',name:'Real Madrid',city:'Madrid',code:'RMA',style:'Attacking',league:'La Liga',leagueCountry:'es',difficulty:'HARD',budget:280000000,reputation:99,stadiumCapacity:83186,colors:['#ffffff','#00529f']},
  {id:'esp-bet',name:'Real Betis',city:'Seville',code:'BET',style:'Technical',league:'La Liga',leagueCountry:'es',difficulty:'HARD',budget:70000000,reputation:82,stadiumCapacity:60721,colors:['#00954c','#ffffff']},
  {id:'esp-soc',name:'Real Sociedad',city:'San Sebastián',code:'RSO',style:'Technical',league:'La Liga',leagueCountry:'es',difficulty:'HARD',budget:65000000,reputation:82,stadiumCapacity:39500,colors:['#0067b1','#ffffff']},
  {id:'esp-sev',name:'Sevilla',city:'Seville',code:'SEV',style:'Balanced',league:'La Liga',leagueCountry:'es',difficulty:'HARD',budget:75000000,reputation:84,stadiumCapacity:43883,colors:['#d71920','#ffffff']},
  {id:'esp-val',name:'Valencia',city:'Valencia',code:'VAL',style:'Attacking',league:'La Liga',leagueCountry:'es',difficulty:'HARD',budget:60000000,reputation:80,stadiumCapacity:49430,colors:['#ffffff','#f36f21']},
  {id:'esp-vil',name:'Villarreal',city:'Villarreal',code:'VIL',style:'Technical',league:'La Liga',leagueCountry:'es',difficulty:'HARD',budget:75000000,reputation:84,stadiumCapacity:23500,colors:['#ffd800','#00529f']},
  // ITALY — SERIE A
  {id:'ita-ata',name:'Atalanta',city:'Bergamo',code:'ATA',style:'Attacking',league:'Serie A',leagueCountry:'it',difficulty:'HARD',budget:90000000,reputation:84,stadiumCapacity:24950,colors:['#1e71b8','#000000']},
  {id:'ita-bol',name:'Bologna',city:'Bologna',code:'BOL',style:'Technical',league:'Serie A',leagueCountry:'it',difficulty:'NORMAL',budget:55000000,reputation:78,stadiumCapacity:36532,colors:['#a51c30','#1d3d78']},
  {id:'ita-cag',name:'Cagliari',city:'Cagliari',code:'CAG',style:'Defensive',league:'Serie A',leagueCountry:'it',difficulty:'CHALLENGE',budget:30000000,reputation:70,stadiumCapacity:16416,colors:['#c8102e','#00205b']},
  {id:'ita-com',name:'Como',city:'Como',code:'COM',style:'Technical',league:'Serie A',leagueCountry:'it',difficulty:'CHALLENGE',budget:45000000,reputation:72,stadiumCapacity:13602,colors:['#004b87','#ffffff']},
  {id:'ita-cre',name:'Cremonese',city:'Cremona',code:'CRE',style:'Balanced',league:'Serie A',leagueCountry:'it',difficulty:'CHALLENGE',budget:28000000,reputation:67,stadiumCapacity:16003,colors:['#d71920','#808080']},
  {id:'ita-fio',name:'Fiorentina',city:'Florence',code:'FIO',style:'Technical',league:'Serie A',leagueCountry:'it',difficulty:'HARD',budget:80000000,reputation:82,stadiumCapacity:43147,colors:['#482683','#ffffff']},
  {id:'ita-gen',name:'Genoa',city:'Genoa',code:'GEN',style:'Balanced',league:'Serie A',leagueCountry:'it',difficulty:'NORMAL',budget:45000000,reputation:76,stadiumCapacity:36599,colors:['#c8102e','#1b3b6f']},
  {id:'ita-hel',name:'Hellas Verona',city:'Verona',code:'VER',style:'Defensive',league:'Serie A',leagueCountry:'it',difficulty:'NORMAL',budget:30000000,reputation:71,stadiumCapacity:39211,colors:['#0057b8','#ffd700']},
  {id:'ita-int',name:'Inter Milan',city:'Milan',code:'INT',style:'Balanced',league:'Serie A',leagueCountry:'it',difficulty:'HARD',budget:180000000,reputation:94,stadiumCapacity:80018,colors:['#0068a8','#000000']},
  {id:'ita-juv',name:'Juventus',city:'Turin',code:'JUV',style:'Balanced',league:'Serie A',leagueCountry:'it',difficulty:'HARD',budget:170000000,reputation:93,stadiumCapacity:41507,colors:['#000000','#ffffff']},
  {id:'ita-laz',name:'Lazio',city:'Rome',code:'LAZ',style:'Technical',league:'Serie A',leagueCountry:'it',difficulty:'HARD',budget:80000000,reputation:84,stadiumCapacity:70834,colors:['#87ceeb','#ffffff']},
  {id:'ita-lec',name:'Lecce',city:'Lecce',code:'LEC',style:'Defensive',league:'Serie A',leagueCountry:'it',difficulty:'CHALLENGE',budget:25000000,reputation:66,stadiumCapacity:33876,colors:['#ffdd00','#e30613']},
  {id:'ita-mil',name:'AC Milan',city:'Milan',code:'MIL',style:'Attacking',league:'Serie A',leagueCountry:'it',difficulty:'HARD',budget:160000000,reputation:92,stadiumCapacity:80018,colors:['#fb090b','#000000']},
  {id:'ita-nap',name:'Napoli',city:'Naples',code:'NAP',style:'Attacking',league:'Serie A',leagueCountry:'it',difficulty:'HARD',budget:140000000,reputation:90,stadiumCapacity:60240,colors:['#12a0d7','#ffffff']},
  {id:'ita-par',name:'Parma',city:'Parma',code:'PAR',style:'Technical',league:'Serie A',leagueCountry:'it',difficulty:'NORMAL',budget:40000000,reputation:74,stadiumCapacity:27906,colors:['#f9dc00','#00529f']},
  {id:'ita-pis',name:'Pisa',city:'Pisa',code:'PIS',style:'Balanced',league:'Serie A',leagueCountry:'it',difficulty:'CHALLENGE',budget:25000000,reputation:65,stadiumCapacity:16709,colors:['#00529f','#000000']},
  {id:'ita-rom',name:'AS Roma',city:'Rome',code:'ROM',style:'Attacking',league:'Serie A',leagueCountry:'it',difficulty:'HARD',budget:120000000,reputation:88,stadiumCapacity:70634,colors:['#8e1f2f','#f0bc42']},
  {id:'ita-sas',name:'Sassuolo',city:'Sassuolo',code:'SAS',style:'Technical',league:'Serie A',leagueCountry:'it',difficulty:'NORMAL',budget:35000000,reputation:72,stadiumCapacity:21584,colors:['#00a651','#000000']},
  {id:'ita-tor',name:'Torino',city:'Turin',code:'TOR',style:'Balanced',league:'Serie A',leagueCountry:'it',difficulty:'NORMAL',budget:50000000,reputation:77,stadiumCapacity:27958,colors:['#8b1e2d','#ffffff']},
  {id:'ita-udi',name:'Udinese',city:'Udine',code:'UDI',style:'Defensive',league:'Serie A',leagueCountry:'it',difficulty:'NORMAL',budget:35000000,reputation:73,stadiumCapacity:25144,colors:['#000000','#ffffff']}
 ];
 NEXORA_DATA.clubs.push(...clubs);
 window.NEXORA_INTERNATIONAL_CLUBS=clubs;
})();
