(()=>{
let audio=null;
function tone(freq,duration=.12,type='sine',gain=.035){try{audio ||= new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.value=gain;o.connect(g);g.connect(audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.stop(audio.currentTime+duration)}catch{}}
function pulse(kind='pass'){const stage=document.getElementById('matchStage');if(!stage)return;stage.classList.remove('crowd-pulse-pass','crowd-pulse-shot','crowd-pulse-goal');void stage.offsetWidth;stage.classList.add('crowd-pulse-'+kind);clearTimeout(window.__nexoraCrowdTimer);window.__nexoraCrowdTimer=setTimeout(()=>stage.classList.remove('crowd-pulse-'+kind),650)}
function ensureStandings(s){const clubs=(window.NEXORA_DATA?.clubs||[]);s.gameState.standings ||= clubs.map(c=>({clubId:c.id,name:c.name,code:c.code,played:0,wins:0,draws:0,losses:0,gf:0,ga:0,gd:0,points:0}));if(!s.gameState.standings.length&&s.gameState.club)s.gameState.standings=[{clubId:s.gameState.club.id,name:s.gameState.club.name,code:s.gameState.club.code,played:0,wins:0,draws:0,losses:0,gf:0,ga:0,gd:0,points:0}];return s.gameState.standings}
function applyResult(e){const x=e.detail||{},s=(()=>{try{return JSON.parse(localStorage.getItem('nexoraCareer')||'null')}catch{return null}})();if(!s?.gameState?.club)return;const matchId=x.matchId||`${s.gameState.date}-${s.gameState.club.id}-${x.homeGoals}-${x.awayGoals}`;if(s.gameState.lastProcessedMatch===matchId)return;const table=ensureStandings(s),home=s.gameState.club,awayName=x.awayName||'Kuzey Liman FK';let h=table.find(t=>t.clubId===home.id||t.code===home.code);if(!h){h={clubId:home.id,name:home.name,code:home.code,played:0,wins:0,draws:0,losses:0,gf:0,ga:0,gd:0,points:0};table.push(h)}let a=table.find(t=>t.name===awayName);if(!a){a={clubId:`ai-${awayName.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`,name:awayName,code:'KLF',played:0,wins:0,draws:0,losses:0,gf:0,ga:0,gd:0,points:0};table.push(a)}const hg=Number(x.homeGoals)||0,ag=Number(x.awayGoals)||0;h.played++;a.played++;h.gf+=hg;h.ga+=ag;a.gf+=ag;a.ga+=hg;h.gd=h.gf-h.ga;a.gd=a.gf-a.ga;if(hg>ag){h.wins++;h.points+=3;a.losses++}else if(hg===ag){h.draws++;h.points++;a.draws++;a.points++}else{h.losses++;a.wins++;a.points+=3}table.sort((u,v)=>v.points-u.points||v.gd-u.gd||v.gf-u.gf||u.name.localeCompare(v.name,'tr'));s.gameState.lastProcessedMatch=matchId;s.gameState.matchHistory ||= [];s.gameState.matchHistory.unshift({id:matchId,date:s.gameState.date,home:home.name,away:awayName,homeGoals:hg,awayGoals:ag,points:hg>ag?3:hg===ag?1:0});s.gameState.matchHistory=s.gameState.matchHistory.slice(0,30);s.gameState.leaguePosition=table.findIndex(t=>t.clubId===home.id)+1;localStorage.setItem('nexoraCareer',JSON.stringify(s));localStorage.setItem('nexoraGameState',JSON.stringify(s.gameState));if(window.NEXORA_CAREER_LOOP?.news)window.NEXORA_CAREER_LOOP.news(s,'Lig tablosuna sonuç işlendi','LEAGUE',`${home.name} ${hg}-${ag} ${awayName} · ${h.points} puan · Lig sırası ${s.gameState.leaguePosition}.`);window.dispatchEvent(new CustomEvent('nexora:standings-updated',{detail:{table,position:s.gameState.leaguePosition}}));window.NEXORA_MEDIA?.render?.()}
function event(e){const x=e.detail||{};if(x.type==='fulltime'){applyResult(e);return}if(x.type==='goal'){pulse('goal');tone(180,.18,'square',.045);setTimeout(()=>tone(260,.22,'sawtooth',.025),90);return}if(x.type==='shot'){pulse('shot');tone(120,.1,'triangle',.025);return}if(x.type==='pass'){pulse('pass');tone(420,.045,'sine',.012);return}if(x.type==='duel'){tone(90,.05,'triangle',.012)}}
function observe(){const log=document.getElementById('matchLog');if(!log)return;if(log.dataset.bridge)return;log.dataset.bridge='1';const seen=new Set();const scan=()=>{[...log.children].forEach(n=>{const text=n.textContent||'',key=text.slice(0,160);if(seen.has(key))return;seen.add(key);if(text.includes('GOAL!'))event({detail:{type:'goal'}});else if(text.includes('pası'))event({detail:{type:'pass'}});else if(text.includes('topu kazandı'))event({detail:{type:'duel'}})})};new MutationObserver(scan).observe(log,{childList:true});scan()}
window.addEventListener('nexora:match-event',event);setInterval(observe,300);window.NEXORA_MATCHDAY_BRIDGE={pulse,tone,applyResult};
})();