(()=>{
let last=0,card=0,inj=0,sub=0,pen=0,shots=0;const K='nexoraCareer';
const get=()=>{try{return JSON.parse(localStorage.getItem(K)||'null')}catch{return null}},put=s=>localStorage.setItem(K,JSON.stringify(s));
const log=t=>{const e=document.getElementById('matchLog');if(!e)return;const d=document.createElement('div');d.className='match-polish-event';d.innerHTML=`<b>${String(last).padStart(2,'0')}'</b>${t}`;e.prepend(d)};const minute=()=>parseInt(document.getElementById('meMinute')?.textContent)||0;
function fx(){if(document.getElementById('nexoraMatchPolishStyle'))return;const s=document.createElement('style');s.id='nexoraMatchPolishStyle';s.textContent='.match-polish-event{padding:5px 8px;border-left:2px solid #b7ff3c;margin:3px 0;font-size:12px}.keeper-save{filter:brightness(1.35);transform:scale(1.01)}.penalty-flash{animation:nexPenalty .7s ease}.setpiece-pulse{animation:nexSet .5s ease}@keyframes nexPenalty{50%{filter:brightness(2)}}@keyframes nexSet{50%{transform:scale(1.015)}}';document.head.appendChild(s)}
function setPiece(m){log(`DURAN TOP · ${Math.random()<.55?'KORNER':'SERBEST VURUŞ'}`);document.getElementById('matchPitch')?.classList.add('setpiece-pulse');setTimeout(()=>document.getElementById('matchPitch')?.classList.remove('setpiece-pulse'),500);window.dispatchEvent(new CustomEvent('nexora:match-event',{detail:{type:'set-piece',minute:m}}))}
function keeper(m){log('🧤 KALECİ KURTARDI · refleks kurtarışı');document.getElementById('matchPitch')?.classList.add('keeper-save');setTimeout(()=>document.getElementById('matchPitch')?.classList.remove('keeper-save'),500);window.dispatchEvent(new CustomEvent('nexora:match-event',{detail:{type:'save',minute:m}}))}
function cardEvent(m){card++;log('🟨 SARI KART · mücadele sertleşiyor');window.dispatchEvent(new CustomEvent('nexora:match-event',{detail:{type:'card',card:'yellow',minute:m}}))}
function injury(m){inj++;log('🚑 SAKATLIK · oyuncu kenarda kontrol ediliyor');window.dispatchEvent(new CustomEvent('nexora:match-event',{detail:{type:'injury',minute:m}}))}
function substitution(m){sub++;log('🔄 OYUNCU DEĞİŞİKLİĞİ · tempo değişiyor');window.dispatchEvent(new CustomEvent('nexora:match-event',{detail:{type:'substitution',minute:m}}))}
function penalty(m){pen++;log('⚠ PENALTI! · beyaz nokta');document.getElementById('matchPitch')?.classList.add('penalty-flash');setTimeout(()=>document.getElementById('matchPitch')?.classList.remove('penalty-flash'),700);window.dispatchEvent(new CustomEvent('nexora:match-event',{detail:{type:'penalty',minute:m}}))}
function consequence(e){const s=get();if(!s?.squad)return;const d=e.detail||{},p=s.squad.find(x=>x.id===d.playerId);if(d.type==='card'&&p)p.morale=Math.max(0,(p.morale||70)-4);if(d.type==='injury'&&p){p.fitness=Math.max(30,(p.fitness||80)-18);p.matchInjury=true}if(d.type==='substitution'&&p)p.fitness=Math.min(100,(p.fitness||70)+8);if(d.type==='penalty'&&p)p.morale=Math.max(0,(p.morale||70)-2);if(d.type==='save')s.gameState.matchStats=s.gameState.matchStats||{};put(s)}
function tick(){const m=minute();if(m<=last||!document.getElementById('matchPitch'))return;last=m;if(m>5&&m%13===0&&Math.random()<.42)setPiece(m);if(m>10&&m%17===0&&Math.random()<.3)keeper(m);if(m>8&&m%19===0&&Math.random()<.35)cardEvent(m);if(m>20&&m%29===0&&Math.random()<.18)injury(m);if(m>30&&m%31===0&&Math.random()<.28)substitution(m);if(m>18&&m%37===0&&Math.random()<.2)penalty(m)}
fx();setInterval(tick,120);window.NEXORA_MATCH_POLISH={reset:()=>{last=0;card=0;inj=0;sub=0;pen=0;shots=0}};window.addEventListener('nexora:match-start',()=>window.NEXORA_MATCH_POLISH.reset());window.addEventListener('nexora:match-event',consequence);window.addEventListener('nexora:match-event',e=>{if(e.detail?.type==='fulltime'){const s=get();if(s){s.gameState.matchIncidentSummary={cards:card,injuries:inj,substitutions:sub,penalties:pen};put(s)}}});
const load=(id,src)=>{if(document.getElementById(id))return;const x=document.createElement('script');x.id=id;x.src=src;document.head.appendChild(x)};load('nexoraFixtureSeasonPatch','fixture-season-patch.js');
})();