(()=>{
let last=0,card=0,inj=0,sub=0,pen=0;
const log=t=>{const e=document.getElementById('matchLog');if(!e)return;const d=document.createElement('div');d.className='match-polish-event';d.innerHTML=`<b>${String(last).padStart(2,'0')}'</b>${t}`;e.prepend(d);};
function minute(){const e=document.getElementById('meMinute');return e?parseInt(e.textContent)||0:0}
function fx(){if(document.getElementById('nexoraMatchPolishStyle'))return;const s=document.createElement('style');s.id='nexoraMatchPolishStyle';s.textContent='.match-polish-event{padding:5px 8px;border-left:2px solid #b7ff3c;margin:3px 0;font-size:12px}.keeper-save{filter:brightness(1.35);transform:scale(1.01)}.penalty-flash{animation:nexPenalty .7s ease}@keyframes nexPenalty{50%{filter:brightness(2)}}.setpiece-pulse{animation:nexSet .5s ease}@keyframes nexSet{50%{transform:scale(1.015)}}';document.head.appendChild(s)}
function setPiece(m){const type=Math.random()<.55?'KORNER':'SERBEST VURUŞ';log(`DURAN TOP · ${type}`);document.getElementById('matchPitch')?.classList.add('setpiece-pulse');setTimeout(()=>document.getElementById('matchPitch')?.classList.remove('setpiece-pulse'),500);window.dispatchEvent(new CustomEvent('nexora:match-event',{detail:{type:type==='KORNER'?'corner':'free-kick',minute:m}}));}
function keeper(m){const side=Math.random()<.5?'home':'away';log(`KALECİ KURTARDI · ${side==='home'?'Ev':'Deplasman'} kalecisi`);const pitch=document.getElementById('matchPitch');pitch?.classList.add('keeper-save');setTimeout(()=>pitch?.classList.remove('keeper-save'),500);window.dispatchEvent(new CustomEvent('nexora:match-event',{detail:{type:'save',team:side,minute:m}}));}
function cardEvent(m){card++;const side=Math.random()<.5?'home':'away';log(`🟨 SARI KART · ${side==='home'?'Ev sahibi':'Deplasman'} oyuncusu`);window.dispatchEvent(new CustomEvent('nexora:match-event',{detail:{type:'card',card:'yellow',team:side,minute:m}}));}
function injury(m){inj++;const side=Math.random()<.5?'home':'away';log(`SAKATLIK · ${side==='home'?'Ev sahibi':'Deplasman'} oyuncusu sağlık ekibi tarafından kontrol ediliyor`);window.dispatchEvent(new CustomEvent('nexora:match-event',{detail:{type:'injury',team:side,minute:m}}));}
function substitution(m){sub++;log(`OYUNCU DEĞİŞİKLİĞİ · Taze oyuncu oyuna girdi, tempo değişiyor`);window.dispatchEvent(new CustomEvent('nexora:match-event',{detail:{type:'substitution',minute:m}}));}
function penalty(m){pen++;const side=Math.random()<.5?'home':'away';log(`PENALTI! · ${side==='home'?'Ev sahibi':'Deplasman'} beyaz noktada`);document.getElementById('matchPitch')?.classList.add('penalty-flash');setTimeout(()=>document.getElementById('matchPitch')?.classList.remove('penalty-flash'),700);window.dispatchEvent(new CustomEvent('nexora:match-event',{detail:{type:'penalty',team:side,minute:m}}));}
function tick(){const m=minute();if(m<=last||!document.getElementById('matchPitch'))return;last=m;if(m>5&&m%13===0&&Math.random()<.42)setPiece(m);if(m>10&&m%17===0&&Math.random()<.3)keeper(m);if(m>8&&m%19===0&&Math.random()<.35)cardEvent(m);if(m>20&&m%29===0&&Math.random()<.18)injury(m);if(m>30&&m%31===0&&Math.random()<.28)substitution(m);if(m>18&&m%37===0&&Math.random()<.2)penalty(m)}
fx();setInterval(tick,120);window.NEXORA_MATCH_POLISH={reset:()=>{last=0;card=0;inj=0;sub=0;pen=0}};window.addEventListener('nexora:match-start',()=>window.NEXORA_MATCH_POLISH.reset());
})();