(() => {
  const FORMATIONS={
    '4-3-3':[[50,88],[20,70],[38,76],[62,76],[80,70],[28,50],[50,56],[72,50],[18,30],[50,22],[82,30]],
    '4-2-3-1':[[50,88],[20,70],[38,76],[62,76],[80,70],[35,58],[65,58],[22,38],[50,32],[78,38],[50,20]],
    '4-4-2':[[50,88],[20,70],[38,76],[62,76],[80,70],[18,48],[38,54],[62,54],[82,48],[38,24],[62,24]]
  };
  let timer=null,minute=0,homeGoals=0,awayGoals=0,finished=false,runtime=[];
  const state=()=>{try{return JSON.parse(localStorage.getItem('nexoraCareer')||'null')}catch{return null}};
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const avg=(players,key)=>Math.round(players.reduce((s,p)=>s+(Number(p[key])||0),0)/Math.max(1,players.length));
  const metrics=players=>({rating:avg(players,'rating'),pace:avg(players,'pace'),passing:avg(players,'passing'),shooting:avg(players,'shooting'),defending:avg(players,'defending'),dribbling:avg(players,'dribbling'),physical:avg(players,'physical'),vision:avg(players,'vision'),stamina:avg(players,'stamina')});
  function emit(type,detail={}){window.dispatchEvent(new CustomEvent('nexora:match-event',{detail:{type,...detail}}));}
  function readCareer(){const s=state();if(!s?.gameState?.club)return null;const players=s.squad||[];const xi=(s.startingXI||[]).map(id=>players.find(p=>p.id===id)).filter(Boolean);return {...s,players,xi,formation:s.formation||s.gameState.formation||'4-3-3'};}
  function openEngine(){const career=readCareer();if(!career||career.xi.length!==11)return;clearInterval(timer);minute=0;homeGoals=0;awayGoals=0;finished=false;runtime=career.xi.map((p,i)=>({id:p.id,name:p.name,pos:p.pos,x:FORMATIONS[career.formation]?.[i]?.[0]||50,y:FORMATIONS[career.formation]?.[i]?.[1]||50,stamina:p.stamina||80}));
    const area=document.getElementById('gameArea');if(!area)return;const m=metrics(career.xi);const attack=clamp(Math.round((m.pace+m.passing+m.shooting+m.dribbling+m.vision)/5),35,95);const defence=clamp(Math.round((m.defending+m.physical+m.pace)/3),35,95);const opponentAttack=62;const opponentDefence=60;
    area.innerHTML=`<div class="match-engine-shell"><div class="match-engine-head"><div><span class="eyebrow">MATCHDAY / MATHEMATICAL ENGINE</span><h3>${career.gameState.club.code} <em>VS</em> KLF</h3><span>90-minute simulation · attack ${attack} · defence ${defence}</span></div><span class="live-badge">● LIVE SIMULATION</span></div><div class="matchday-stage" id="matchStage"><div class="matchday-crowd" id="matchCrowd"></div><div class="matchday-score"><b id="meHome">0</b><span>${career.gameState.club.code} · <i id="meMinute">00'</i> · KLF</span><b id="meAway">0</b></div><div class="matchday-pitch-wrap"><div class="matchday-pitch" id="matchPitch"></div></div><div class="matchday-events"><span class="matchday-minute" id="eventMinute">00'</span><span class="matchday-event" id="eventText">Teams are ready. Kick-off.</span></div></div><div class="match-log" id="matchLog"></div><div class="matchday-controls"><button class="primary" id="mePlay">PLAY 90 MINUTES</button><button class="secondary" id="meSkip">SIMULATE FULL MATCH</button></div><div id="matchResult"></div></div>`;
    const pitch=document.getElementById('matchPitch');runtime.forEach((p,i)=>{const el=document.createElement('div');el.className='match-player';el.dataset.id=p.id;el.style.left=`${p.x}%`;el.style.top=`${p.y}%`;el.innerHTML=`<span>${p.pos}</span><small>${p.name.split(' ')[0]}</small>`;pitch.appendChild(el);});const ball=document.createElement('div');ball.className='match-ball';ball.id='matchBall';ball.style.left='50%';ball.style.top='50%';pitch.appendChild(ball);
    const log=document.getElementById('matchLog');const addLog=(text,kind='')=>{const d=document.createElement('div');d.className=kind;d.innerHTML=`<b>${String(minute).padStart(2,'0')}'</b>${text}`;log.prepend(d);while(log.children.length>10)log.lastElementChild.remove();document.getElementById('eventText').textContent=text;document.getElementById('eventMinute').textContent=`${String(minute).padStart(2,'0')}'`;};
    const movePlayers=()=>{runtime.forEach(p=>{const fatigue=clamp((90-p.stamina)/100,0,.45);const drift=(p.pos==='ST'||p.pos==='LW'||p.pos==='RW')?5:3;p.x=clamp(p.x+(Math.random()-.5)*drift*(1-fatigue),5,95);p.y=clamp(p.y+(Math.random()-.5)*drift*(1-fatigue),5,95);const el=pitch.querySelector(`[data-id="${p.id}"]`);if(el){el.style.left=`${p.x}%`;el.style.top=`${p.y}%`;}p.stamina=clamp(p.stamina-(0.08+Math.random()*.08),45,100);});const b=document.getElementById('matchBall');if(b){b.style.left=`${clamp(50+(Math.random()-.5)*70,8,92)}%`;b.style.top=`${clamp(50+(Math.random()-.5)*70,8,92)}%`;}};
    const goal=team=>{if(team==='home'){homeGoals++;document.getElementById('meHome').textContent=homeGoals;const scorer=career.xi[Math.floor(Math.random()*career.xi.length)];addLog(`GOAL! ${scorer.name} finishes the chance.`, 'goal');emit('goal',{team:'home',scorer:scorer.name,minute});}else{awayGoals++;document.getElementById('meAway').textContent=awayGoals;addLog(`GOAL! KLF converts the opening.`, 'goal');emit('goal',{team:'away',minute});}const flash=document.createElement('div');flash.className='match-goal-flash';document.getElementById('matchStage').appendChild(flash);setTimeout(()=>flash.remove(),700);};
    const tick=()=>{if(finished)return;minute++;document.getElementById('meMinute').textContent=`${String(minute).padStart(2,'0')}'`;movePlayers();const homeChance=0.055+Math.max(0,attack-opponentDefence)*0.0022;const awayChance=0.045+Math.max(0,opponentAttack-defence)*0.002;const roll=Math.random();if(roll<homeChance)goal('home');else if(roll<homeChance+awayChance)goal('away');else if(roll<homeChance+awayChance+0.10)addLog(`${career.gameState.club.name} creates a chance through passing and movement.`);else if(roll<homeChance+awayChance+0.17)addLog(`KLF presses high. Defensive structure is tested.`);else if(roll<homeChance+awayChance+0.20)addLog(`Midfield duel. Vision ${m.vision} is controlling the tempo.`);if(minute>=90)finish(career);};
    document.getElementById('mePlay').onclick=()=>{document.getElementById('mePlay').disabled=true;emit('kickoff',{minute:0});timer=setInterval(tick,180);};document.getElementById('meSkip').onclick=()=>{clearInterval(timer);while(minute<90)tick();};
  }
  function finish(career){if(finished)return;finished=true;clearInterval(timer);const boardDelta=homeGoals>awayGoals?5:homeGoals===awayGoals?1:-5;const repDelta=homeGoals>awayGoals?2:homeGoals===awayGoals?1:-2;career.gameState.boardConfidence=clamp((career.gameState.boardConfidence||60)+boardDelta,0,100);career.gameState.reputation=Math.max(0,(career.gameState.reputation||50)+repDelta);localStorage.setItem('nexoraGameState',JSON.stringify(career.gameState));localStorage.setItem('nexoraCareer',JSON.stringify({...career,gameState:career.gameState}));document.getElementById('matchResult').innerHTML=`<div class="match-result">FULL TIME · <strong>${homeGoals} — ${awayGoals}</strong> · ${homeGoals>awayGoals?'WIN':'DRAW / LOSS'} · Board ${boardDelta>=0?'+':''}${boardDelta}</div>`;document.getElementById('mePlay').disabled=true;emit('fulltime',{homeGoals,awayGoals});}
  function intercept(e){const t=e.target.closest?.('#matchFromSquad,#startMatchTactic');if(!t)return;e.preventDefault();e.stopImmediatePropagation();openEngine();}
  document.addEventListener('click',intercept,true);
  window.NEXORA_MATCH_ENGINE={start:openEngine};
})();