(() => {
  const FORMATIONS={
    '4-3-3':[[50,88],[20,70],[38,76],[62,76],[80,70],[28,50],[50,56],[72,50],[18,30],[50,22],[82,30]],
    '4-2-3-1':[[50,88],[20,70],[38,76],[62,76],[80,70],[35,58],[65,58],[22,38],[50,32],[78,38],[50,20]],
    '4-4-2':[[50,88],[20,70],[38,76],[62,76],[80,70],[18,48],[38,54],[62,54],[82,48],[38,24],[62,24]]
  };
  const COMMANDS={balanced:{label:'DENGELİ',desc:'Takım normal riskle oynuyor.',attack:0,defence:0,tempo:0},press:{label:'ÖN ALAN PRESİ',desc:'Oyuncular önde baskıya çıkıyor.',attack:7,defence:4,tempo:8},counter:{label:'HIZLI HÜCUM',desc:'Top kazanılınca ileri koşular başlıyor.',attack:9,defence:-2,tempo:10},possession:{label:'TOPA SAHİP OL',desc:'Pas bağlantıları ve sabır artırıldı.',attack:4,defence:3,tempo:-5},lowblock:{label:'GERİDE BEKLE',desc:'Savunma hattı geriye çekildi.',attack:-6,defence:10,tempo:-8},wide:{label:'KANATLARI KULLAN',desc:'Kanat oyuncuları daha geniş konumlanıyor.',attack:6,defence:0,tempo:4}};
  let timer=null,minute=0,homeGoals=0,awayGoals=0,finished=false,runtime=[],command='balanced',commandState=COMMANDS.balanced;
  const state=()=>{try{return JSON.parse(localStorage.getItem('nexoraCareer')||'null')}catch{return null}};
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const avg=(players,key)=>Math.round(players.reduce((s,p)=>s+(Number(p[key])||0),0)/Math.max(1,players.length));
  const metrics=players=>({rating:avg(players,'rating'),pace:avg(players,'pace'),passing:avg(players,'passing'),shooting:avg(players,'shooting'),defending:avg(players,'defending'),dribbling:avg(players,'dribbling'),physical:avg(players,'physical'),vision:avg(players,'vision'),stamina:avg(players,'stamina')});
  function emit(type,detail={}){window.dispatchEvent(new CustomEvent('nexora:match-event',{detail:{type,...detail}}));}
  function readCareer(){const s=state();if(!s?.gameState?.club)return null;const players=s.squad||[];const xi=(s.startingXI||[]).map(id=>players.find(p=>p.id===id)).filter(Boolean);return {...s,players,xi,formation:s.formation||s.gameState.formation||'4-3-3'};}
  function openEngine(){const career=readCareer();if(!career||career.xi.length!==11)return;clearInterval(timer);minute=0;homeGoals=0;awayGoals=0;finished=false;command='balanced';commandState=COMMANDS.balanced;runtime=career.xi.map((p,i)=>({id:p.id,name:p.name,pos:p.pos,x:FORMATIONS[career.formation]?.[i]?.[0]||50,y:FORMATIONS[career.formation]?.[i]?.[1]||50,stamina:p.stamina||80}));
    const area=document.getElementById('gameArea');if(!area)return;const m=metrics(career.xi);const attack=clamp(Math.round((m.pace+m.passing+m.shooting+m.dribbling+m.vision)/5),35,95);const defence=clamp(Math.round((m.defending+m.physical+m.pace)/3),35,95);const opponentAttack=62,opponentDefence=60;const isHome=Math.random()>.5;const homeName=career.gameState.club.name;const awayName='KLF';const homeFanBase=isHome?1.12:.91;const awayFanBase=isHome?.91:1.12;const fanIntensity=isHome?78:64;
    area.innerHTML=`<div class="match-engine-shell"><div class="match-engine-head"><div><span class="eyebrow">MATCHDAY / LIVE TACTICAL ENGINE</span><h3>${isHome?homeName:awayName} <em>VS</em> ${isHome?awayName:homeName}</h3><span>${isHome?'EV SAHİBİ':'DEPLASMAN'} · ${career.formation} · Tribün etkisi ${fanIntensity}%</span></div><span class="live-badge">● LIVE MATCH</span></div><div class="matchday-stage ${isHome?'home-match':'away-match'}" id="matchStage"><div class="matchday-crowd home-crowd" id="homeCrowd"><i></i><i></i><i></i><i></i><i></i><span>HOME SUPPORTERS</span></div><div class="matchday-crowd away-crowd" id="awayCrowd"><i></i><i></i><i></i><span>AWAY SUPPORTERS</span></div><div class="matchday-score"><b id="meHome">0</b><span>${isHome?homeName:awayName} · <i id="meMinute">00'</i> · ${isHome?awayName:homeName}</span><b id="meAway">0</b></div><div class="matchday-pitch-wrap"><div class="matchday-pitch" id="matchPitch"></div></div><div class="coach-box"><div class="coach-title"><strong>TECHNICAL AREA</strong><span id="coachMood">MAÇ BAŞI</span></div><div class="coach-command-grid">${Object.entries(COMMANDS).map(([id,c])=>`<button class="coach-command ${id==='balanced'?'active':''}" data-command="${id}">${c.label}</button>`).join('')}</div><div class="coach-message" id="coachMessage">Kenardan komut ver. Oyuncular sonraki aksiyonlarda talimatı uygulayacak.</div></div><div class="matchday-events"><span class="matchday-minute" id="eventMinute">00'</span><span class="matchday-event" id="eventText">Takımlar sahada. Teknik adamlar son talimatları veriyor.</span></div></div><div class="match-log" id="matchLog"></div><div class="matchday-controls"><button class="primary" id="mePlay">MAÇA BAŞLA</button><button class="secondary" id="meSkip">MAÇI SİMÜLE ET</button></div><div id="matchResult"></div></div>`;
    const pitch=document.getElementById('matchPitch');runtime.forEach((p,i)=>{const el=document.createElement('div');el.className=`match-player role-${String(p.pos).toLowerCase()}`;el.dataset.id=p.id;el.style.left=`${p.x}%`;el.style.top=`${p.y}%`;el.innerHTML=`<div class="player-silhouette"><span class="player-head"></span><span class="player-body"></span><span class="player-legs"></span></div><b>${p.pos}</b><small>${p.name.split(' ')[0]}</small>`;pitch.appendChild(el);});const ball=document.createElement('div');ball.className='match-ball';ball.id='matchBall';ball.style.left='50%';ball.style.top='50%';pitch.appendChild(ball);
    const log=document.getElementById('matchLog');const addLog=(text,kind='')=>{const d=document.createElement('div');d.className=kind;d.innerHTML=`<b>${String(minute).padStart(2,'0')}'</b>${text}`;log.prepend(d);while(log.children.length>10)log.lastElementChild.remove();document.getElementById('eventText').textContent=text;document.getElementById('eventMinute').textContent=`${String(minute).padStart(2,'0')}'`;};
    const applyCommand=id=>{if(finished)return;command=id;commandState=COMMANDS[id];document.querySelectorAll('.coach-command').forEach(b=>b.classList.toggle('active',b.dataset.command===id));document.getElementById('coachMessage').textContent=`${commandState.label}: ${commandState.desc} Oyuncular talimatı uyguluyor.`;document.getElementById('coachMood').textContent='TALİMAT UYGULANIYOR';addLog(`TEKNİK DİREKTİF: ${commandState.label}. Oyuncular pozisyonlarını ve risk seviyesini değiştiriyor.`,'command');emit('coach-command',{command:id,minute});};
    document.querySelectorAll('.coach-command').forEach(b=>b.onclick=()=>applyCommand(b.dataset.command));
    const movePlayers=()=>{const ballX=clamp(50+(Math.random()-.5)*70,8,92),ballY=clamp(50+(Math.random()-.5)*70,8,92);runtime.forEach(p=>{const role=p.pos;let targetX=50,targetY=50;if(role==='GK'){targetX=50;targetY=88;}else if(['CB','LB','RB','DEF'].some(v=>role.includes(v))){targetY=clamp(70+(ballY-50)*.18-commandState.defence*.35,55,88);targetX=clamp(p.x+(ballX-50)*.08,8,92);}else if(['ST','CF'].some(v=>role.includes(v))){targetY=clamp(24+(ballY-50)*.25+commandState.attack*.35,10,45);targetX=clamp(p.x+(ballX-50)*.18,8,92);}else{targetY=clamp(52+(ballY-50)*.28-commandState.defence*.15,30,70);targetX=clamp(p.x+(ballX-50)*.14+(command==='wide'?(p.x<50?-6:6):0),8,92);}const fatigue=clamp((90-p.stamina)/100,0,.5);const speed=(0.12+(Number(p.pace)||60)/500)*(1-fatigue);p.x+=(targetX-p.x)*speed;p.y+=(targetY-p.y)*speed;p.stamina=clamp(p.stamina-(0.08+Math.random()*.08+Math.max(0,commandState.tempo)*.004),35,100);const el=pitch.querySelector(`[data-id="${p.id}"]`);if(el){el.style.left=`${p.x}%`;el.style.top=`${p.y}%`;el.classList.toggle('pressing',command==='press');el.classList.toggle('running',command==='counter'||command==='wide');}});const b=document.getElementById('matchBall');if(b){b.style.left=`${ballX}%`;b.style.top=`${ballY}%`;}};
    const goal=team=>{if(team==='home'){homeGoals++;document.getElementById('meHome').textContent=homeGoals;const attackers=career.xi.filter(p=>/ST|CF|LW|RW|AM/.test(p.pos));const pool=attackers.length?attackers:career.xi;const scorer=pool[Math.floor(Math.random()*pool.length)];addLog(`GOAL! ${scorer.name} finishes the move. ${commandState.label} worked.`,'goal');emit('goal',{team:'home',scorer:scorer.name,minute});}else{awayGoals++;document.getElementById('meAway').textContent=awayGoals;addLog(`GOAL! ${awayName} breaks through the defensive line.`,'goal');emit('goal',{team:'away',minute});}const flash=document.createElement('div');flash.className='match-goal-flash';document.getElementById('matchStage').appendChild(flash);setTimeout(()=>flash.remove(),700);};
    const tick=()=>{if(finished)return;minute++;document.getElementById('meMinute').textContent=`${String(minute).padStart(2,'0')}'`;movePlayers();const tacticalAttack=attack+commandState.attack;const tacticalDefence=defence+commandState.defence;const homeChance=(0.055+Math.max(0,tacticalAttack-opponentDefence)*0.0022)*homeFanBase;const awayChance=(0.045+Math.max(0,opponentAttack-tacticalDefence)*0.002)*awayFanBase;const roll=Math.random();if(roll<homeChance)goal('home');else if(roll<homeChance+awayChance)goal('away');else if(roll<homeChance+awayChance+0.10)addLog(`${homeName} creates a chance. ${commandState.label} is shaping the movement.`);else if(roll<homeChance+awayChance+0.17)addLog(`${isHome?'Home':'Away'} supporters raise the intensity. Fan pressure: ${fanIntensity}%.`);else if(roll<homeChance+awayChance+0.20)addLog(`Midfield duel. Vision ${m.vision} is controlling the tempo.`);if(minute%15===0)addLog(`Coach update: ${commandState.label}. Oyuncular talimatı sahada uyguluyor.`,'command');if(minute>=90)finish(career);};
    document.getElementById('mePlay').onclick=()=>{document.getElementById('mePlay').disabled=true;emit('kickoff',{minute:0,isHome});addLog(`${isHome?'Ev sahibi':'Deplasman'} avantajı aktif. Tribün etkisi ${fanIntensity}%.`);timer=setInterval(tick,180);};document.getElementById('meSkip').onclick=()=>{clearInterval(timer);while(minute<90)tick();};
  }
  function finish(career){if(finished)return;finished=true;clearInterval(timer);const boardDelta=homeGoals>awayGoals?5:homeGoals===awayGoals?1:-5;const repDelta=homeGoals>awayGoals?2:homeGoals===awayGoals?1:-2;career.gameState.boardConfidence=clamp((career.gameState.boardConfidence||60)+boardDelta,0,100);career.gameState.reputation=Math.max(0,(career.gameState.reputation||50)+repDelta);localStorage.setItem('nexoraGameState',JSON.stringify(career.gameState));localStorage.setItem('nexoraCareer',JSON.stringify({...career,gameState:career.gameState}));document.getElementById('matchResult').innerHTML=`<div class="match-result">FULL TIME · <strong>${homeGoals} — ${awayGoals}</strong> · ${homeGoals>awayGoals?'WIN':homeGoals===awayGoals?'DRAW':'LOSS'} · Board ${boardDelta>=0?'+':''}${boardDelta}</div>`;document.getElementById('mePlay').disabled=true;document.getElementById('coachMessage').textContent='Maç bitti. Teknik direktiflerin oyuncu davranışlarını etkiledi.';emit('fulltime',{homeGoals,awayGoals});}
  function intercept(e){const t=e.target.closest?.('#matchFromSquad,#startMatchTactic');if(!t)return;e.preventDefault();e.stopImmediatePropagation();openEngine();}
  document.addEventListener('click',intercept,true);window.NEXORA_MATCH_ENGINE={start:openEngine};
})();