(()=>{
const SKIN=['#6b4635','#8b5b43','#ad7658','#c98f69','#e1ad86','#f0c39f'];const HAIR=['#161313','#2a1b17','#4b2f20','#6b472e','#92704e','#b7a27c'];
const names=['Mert Kaya','Luka Marin','Deniz Aksoy','Aras Yıldırım','Miloš Vuković','Emre Kılıç','Jonas Berg','Tomas Silva'];
const st=()=>{try{return JSON.parse(localStorage.getItem('nexoraCareer')||'null')}catch{return null}};const save=s=>localStorage.setItem('nexoraCareer',JSON.stringify(s));
function appearance(p){if(!p)return p;if(p.skinTone)return p;p.skinTone=SKIN[Math.floor(Math.random()*SKIN.length)];p.hairColor=HAIR[Math.floor(Math.random()*HAIR.length)];p.hairStyle=['SHORT','FADE','CURLY','WAVY','LONG','BUZZ'][Math.floor(Math.random()*6)];p.height=170+Math.floor(Math.random()*25);return p}
function ensurePlayers(s){(s.squad||[]).forEach(appearance);(s.gameState.transferMarket?.players||[]).forEach(appearance);(s.gameState.transferMarket?.scoutReports||[]).forEach(appearance);save(s)}
function portrait(p){return `<div class="player-portrait" style="--skin:${p.skinTone};--hair:${p.hairColor};--kit:${squadKit()}"><i class="portrait-hair"></i><i class="portrait-head"></i><i class="portrait-body"></i></div>`}function squadKit(){return '#315f48'}
function addNews(s,title,tag='TRANSFER',detail=''){s.gameState.media ||= {news:[],events:[]};s.gameState.media.news.unshift({id:Date.now(),title,tag,detail,date:s.gameState.date});s.gameState.media.news=s.gameState.media.news.slice(0,12);save(s)}
function headlineFor(p,fee,club){if((p.rating||0)>=78||fee>=2500000||p.wage>=40000)return `${p.name} için flaş transfer: ${club} yıldızını kadrosuna kattı`;if((p.potential||0)>=85)return `${p.name}: Geleceğin yıldızı ${club} ile imzaladı`;return `${p.name} yeni takımına katıldı`}
function render(){const s=st(),dash=document.getElementById('dashboard');if(!s?.gameState?.club||!dash)return;ensurePlayers(s);s.gameState.media ||= {news:[],events:[]};let host=document.getElementById('worldMedia');if(!host){host=document.createElement('section');host.id='worldMedia';host.className='world-media';dash.appendChild(host)}const news=s.gameState.media.news||[];const latest=s.gameState.media.latestEvent;host.innerHTML=`<div class="media-card"><div class="media-head"><div><span class="eyebrow">NEXORA SPORTS DESK / WORLD MEDIA</span><h3>FUTBOL GÜNDEMİ</h3><p>Transferler, yıldızlar, kulüp hikâyeleri ve dünyadan son dakika gelişmeleri.</p></div><span class="news-badge">LIVE</span></div><div class="news-list">${news.length?news.map(n=>`<article class="news-item"><b class="news-badge">${n.tag}</b><div><strong>${n.title}</strong><span>${n.detail||'Nexora Sports Desk özel haberi.'}</span></div><time>${n.date||''}</time></article>`).join(''):'<div class="academy-empty">Dünya sessiz. İlk büyük hamleni yap.</div>'}</div></div><div class="media-card"><span class="eyebrow">SPECIAL COVERAGE</span><h3>${latest?.title||'TRANSFER MERKEZİ'}</h3>${latest?.player?`<div class="portrait-card">${portrait(latest.player)}<div><strong>${latest.player.name}</strong><span>${latest.fee?`€${(latest.fee/1000000).toFixed(2)}M BONServis`:''}</span></div></div>`:''}${latest?.airport?`<div class="airport-stage"><div class="airport-terminal"></div><div class="airport-lights"></div><div class="airport-plane"></div><div class="ataturk-silhouette"></div><div class="airport-quote">“İstikbal göklerdedir.”<small>Gazi Mustafa Kemal Atatürk</small></div></div>`:`<div class="signing-stage"><div class="portrait-card" style="position:absolute;left:20px;bottom:18px">${latest?.player?portrait(latest.player):''}</div></div>`}</div>`}
function announceTransfer(p,fee,club){const s=st();if(!s)return;appearance(p);const big=(p.rating||0)>=78||fee>=2500000||p.wage>=40000;addNews(s,headlineFor(p,fee,club),'BREAKING',`${p.pos||'PLAYER'} · OVR ${p.rating||'-'} · POT ${p.potential||'-'}`);s.gameState.media.latestEvent={title:big?'YILDIZ TRANSFER / ÖZEL YAYIN':'YENİ İMZA',player:p,fee,airport:big,date:s.gameState.date};save(s);render();if(big)showPresentation(p,fee,club)}
function showPresentation(p,fee,club){const old=document.getElementById('transferPresentation');if(old)old.remove();const d=document.createElement('div');d.id='transferPresentation';d.className='modal';d.style.display='flex';d.innerHTML=`<div class="modal-card media-event"><button class="close" id="closePresentation">×</button><span class="eyebrow">NEXORA SPORTS / LIVE</span><h2>${p.name} İSTANBUL'DA!</h2><p>${club} yeni yıldızını <b>€${(fee/1000000).toFixed(2)}M</b> bonservisle kadrosuna kattı.</p><div class="airport-stage"><div class="airport-terminal"></div><div class="airport-lights"></div><div class="airport-plane"></div><div class="ataturk-silhouette"></div><div class="airport-quote">“İstikbal göklerdedir.”<small>Gazi Mustafa Kemal Atatürk</small></div></div><p class="eyebrow" style="margin-top:12px">NEXORA HAVALİMANLARI · RESMİ KARŞILAMA</p><button class="primary full" id="closePresentation2">CONTINUE →</button></div>`;document.body.appendChild(d);d.querySelector('#closePresentation').onclick=()=>d.remove();d.querySelector('#closePresentation2').onclick=()=>d.remove()}
window.NEXORA_MEDIA={appearance,announceTransfer,addNews,render};window.addEventListener('load',render);window.addEventListener('nexora:career-ready',render);window.addEventListener('nexora:transfer-updated',render);})();