(() => {
  const MARKET_NAMES=['Luka Marin','Deniz Aksoy','Aras Yıldırım','Miloš Vuković','Emre Kılıç','Jonas Berg','Tomas Silva','Baran Keskin','Niko Petrov','Caner Öz'];
  const ROLES=[['ST','FORWARD'],['RW','WINGER'],['AM','CREATOR'],['CM','PLAYMAKER'],['DM','ANCHOR'],['CB','DEFENDER'],['LB','FULL BACK'],['RB','FULL BACK'],['GK','KEEPER']];
  const SCOUTS=[
    {id:'data',name:'DATA SCOUT',cost:90000,days:7,quality:5,desc:'Piyasa verisini tarar; değer sapmalarını bulur.'},
    {id:'youth',name:'YOUTH SCOUT',cost:120000,days:10,quality:9,desc:'18–21 yaş aralığında yüksek potansiyel arar.'},
    {id:'international',name:'INTERNATIONAL SCOUT',cost:180000,days:14,quality:12,desc:'Yurt dışı pazardan gizli yetenek çıkarır.'}
  ];
  const state=()=>{try{return JSON.parse(localStorage.getItem('nexoraCareer')||'null')}catch{return null}};
  const save=s=>localStorage.setItem('nexoraCareer',JSON.stringify(s));
  const money=v=>`€${(v/1000000).toFixed(2)}M`;
  const rand=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
  const ensure=()=>{const s=state();if(!s?.gameState?.club)return null;s.gameState.transferMarket ||= {players:[],scoutReports:[],scouts:[],offers:[],lastRefresh:s.gameState.date};s.gameState.transferMarket.players ||= [];s.gameState.transferMarket.scoutReports ||= [];s.gameState.transferMarket.scouts ||= [];s.gameState.transferMarket.offers ||= [];return s};
  function generateMarket(s){const m=s.gameState.transferMarket;if(m.players.length)return;for(let i=0;i<12;i++){const [pos,role]=ROLES[rand(0,ROLES.length-1)];const age=rand(18,31);const rating=rand(58,78);const potential=Math.min(92,rating+rand(2,17)+(age<22?5:0));m.players.push({id:`mkt-${Date.now()}-${i}`,name:MARKET_NAMES[i%MARKET_NAMES.length],age,pos,role,rating,potential,pace:rand(55,88),passing:rand(55,88),shooting:rand(50,88),defending:rand(45,86),value:Math.max(180000,Math.round((rating*rating*900)+(potential>82?450000:0)),),wage:rand(8,55)*1000,contract:rand(1,4),club:['Kuzey Liman FK','Bosphorus United','Ege Spor','Anadolu 1963'][i%4]});}save(s)}
  function refresh(s){const m=s.gameState.transferMarket;m.players=[];m.lastRefresh=s.gameState.date;generateMarket(s)}
  function scout(s,type){const cfg=SCOUTS.find(x=>x.id===type),m=s.gameState.transferMarket;if(!cfg||s.gameState.money<cfg.cost)return alert(`Scout için ${money(cfg?.cost||0)} gerekli.`);s.gameState.money-=cfg.cost;const pos=ROLES[rand(0,ROLES.length-1)];const age=type==='youth'?rand(16,21):rand(18,25);const rating=rand(52,73)+Math.floor(cfg.quality/4);const potential=Math.min(95,rating+rand(8,22)+cfg.quality);const report={id:`report-${Date.now()}`,name:MARKET_NAMES[rand(0,MARKET_NAMES.length-1)],age,pos:pos[0],role:pos[1],rating,potential,value:Math.max(100000,potential*potential*800),wage:rand(4,35)*1000,confidence:Math.min(98,65+cfg.quality*2+rand(0,20)),source:cfg.name};m.scoutReports.unshift(report);m.scoutReports=m.scoutReports.slice(0,8);save(s);render();window.dispatchEvent(new Event('nexora:transfer-updated'))}
  function buy(id,source='market'){const s=ensure();if(!s)return;generateMarket(s);const m=s.gameState.transferMarket;const p=(source==='report'?m.scoutReports.find(x=>x.id===id):m.players.find(x=>x.id===id));if(!p)return;const fee=Math.round(p.value*(1+rand(5,22)/100));if(s.gameState.money<fee)return alert(`Yetersiz bütçe. Bonservis: ${money(fee)}`);s.gameState.money-=fee;const player={id:`signed-${Date.now()}`,name:p.name,pos:p.pos,role:p.role,age:p.age,rating:p.rating,potential:p.potential,pace:p.pace||rand(55,85),passing:p.passing||rand(55,85),shooting:p.shooting||rand(50,85),defending:p.defending||rand(45,85),dribbling:rand(50,86),physical:rand(50,88),vision:rand(50,88),stamina:rand(55,90),fitness:100,morale:70,value:p.value,wage:p.wage};s.squad.push(player);m.players=m.players.filter(x=>x.id!==id);m.scoutReports=m.scoutReports.filter(x=>x.id!==id);save(s);alert(`${p.name} kadroya katıldı. Bonservis: ${money(fee)}`);render();window.dispatchEvent(new Event('nexora:transfer-updated'))}
  function promoteYouth(id){const s=ensure();if(!s)return;const a=s.gameState.facilities?.academy;if(!a)return;const p=(a.signed||[]).find(x=>x.id===id);if(!p)return;s.squad.push({...p,id:`pro-${Date.now()}`,contract:'first-team',fitness:100,morale:78,pace:rand(55,82),passing:rand(50,82),shooting:rand(48,82),defending:rand(45,82),dribbling:rand(50,84),physical:rand(50,84),vision:rand(50,84),stamina:rand(55,88),value:Math.max(p.value,p.potential*22000)});a.signed=a.signed.filter(x=>x.id!==id);save(s);alert(`${p.name} A takıma yükseldi.`);render();window.dispatchEvent(new Event('nexora:transfer-updated'))}
  function sell(id){const s=ensure();if(!s)return;const p=s.squad.find(x=>x.id===id);if(!p)return;const fee=Math.max(50000,Math.round((p.value||100000)*(0.82+rand(0,35)/100)));s.gameState.money+=fee;s.squad=s.squad.filter(x=>x.id!==id);s.startingXI=(s.startingXI||[]).filter(x=>x!==id);save(s);alert(`${p.name} satıldı. Kulüp geliri: ${money(fee)}`);render();window.dispatchEvent(new Event('nexora:transfer-updated'))}
  function render(){const s=ensure(),host=document.getElementById('transferMarket');if(!s||!host)return;generateMarket(s);const m=s.gameState.transferMarket;const youth=s.gameState.facilities?.academy?.signed||[];host.innerHTML=`<div class="transfer-head"><div><span class="eyebrow">SPORTING DIRECTOR / TRANSFER HUB</span><h3>TRANSFER & SCOUTING</h3><p>Oyuncu bul, değerini analiz et, pazarlık yap ve kadronun geleceğini kur.</p></div><button class="secondary" id="refreshMarket">REFRESH MARKET</button></div><div class="scout-grid">${SCOUTS.map(x=>`<article class="scout-card"><span class="eyebrow">${x.name}</span><b>${money(x.cost)}</b><p>${x.desc}</p><button class="primary full" data-scout="${x.id}">SEND SCOUT →</button></article>`).join('')}</div><div class="transfer-section"><div class="section-title"><span>MARKET</span><b>${m.players.length} TARGETS</b></div><div class="market-list">${m.players.map(p=>`<div class="market-player"><div><strong>${p.name}</strong><span>${p.age} YAŞ · ${p.pos} · ${p.club}</span></div><div><b>OVR ${p.rating}</b><small>POT ${p.potential}</small></div><button class="primary" data-buy="${p.id}">SCOUT + BUY</button></div>`).join('')}</div></div><div class="transfer-section"><div class="section-title"><span>SCOUT REPORTS</span><b>${m.scoutReports.length} REPORTS</b></div><div class="market-list">${m.scoutReports.length?m.scoutReports.map(p=>`<div class="market-player discovered"><div><strong>${p.name}</strong><span>${p.age} YAŞ · ${p.pos} · ${p.source}</span></div><div><b>OVR ${p.rating}</b><small>POT ${p.potential} · ${p.confidence}% CONF.</small></div><button class="primary" data-report-buy="${p.id}">SIGN →</button></div>`).join(''):'<div class="academy-empty">Henüz keşif raporu yok. Scout gönder.</div>'}</div></div><div class="transfer-section"><div class="section-title"><span>ACADEMY PIPELINE</span><b>${youth.length} READY</b></div><div class="market-list">${youth.length?youth.map(p=>`<div class="market-player youth-target"><div><strong>${p.name}</strong><span>${p.age} YAŞ · ${p.pos} · HOMEGROWN</span></div><div><b>OVR ${p.rating}</b><small>POT ${p.potential}</small></div><button class="primary" data-promote="${p.id}">A TAKIMA AL →</button></div>`).join(''):'<div class="academy-empty">Akademiden imzalanan gençler burada görünür.</div>'}</div></div><div class="transfer-section"><div class="section-title"><span>FIRST TEAM MARKET VALUE</span><b>${s.squad.length} PLAYERS</b></div><div class="market-list">${s.squad.slice().sort((a,b)=>(b.value||0)-(a.value||0)).slice(0,10).map(p=>`<div class="market-player"><div><strong>${p.name}</strong><span>${p.age} YAŞ · ${p.pos}</span></div><div><b>OVR ${p.rating}</b><small>VALUE ${money(p.value||0)}</small></div><button class="secondary" data-sell="${p.id}">LIST / SELL</button></div>`).join('')}</div></div>`;
    host.querySelector('#refreshMarket').onclick=()=>{refresh(s);render()};host.querySelectorAll('[data-scout]').forEach(b=>b.onclick=()=>scout(s,b.dataset.scout));host.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>buy(b.dataset.buy));host.querySelectorAll('[data-report-buy]').forEach(b=>b.onclick=()=>buy(b.dataset.reportBuy,'report'));host.querySelectorAll('[data-promote]').forEach(b=>b.onclick=()=>promoteYouth(b.dataset.promote));host.querySelectorAll('[data-sell]').forEach(b=>b.onclick=()=>sell(b.dataset.sell));}
  function mount(){const dashboard=document.getElementById('dashboard');if(!dashboard||!ensure())return;let host=document.getElementById('transferMarket');if(!host){host=document.createElement('section');host.id='transferMarket';host.className='transfer-market';const fac=document.getElementById('clubFacilities');(fac||document.querySelector('.dashboard-panels'))?.insertAdjacentElement('afterend',host)}render()}
  window.addEventListener('load',mount);window.addEventListener('nexora:career-ready',mount);window.addEventListener('nexora:transfer-updated',mount);window.NEXORA_TRANSFER={render,scout,buy,sell,promoteYouth};
})();