(()=>{
const K='nexoraCareer';const get=()=>{try{return JSON.parse(localStorage.getItem(K)||'null')}catch{return null}};const save=s=>localStorage.setItem(K,JSON.stringify(s));
const CLUBS=[['Bosphorus United','Istanbul'],['Capital 1907','Ankara'],['Aegean Stars','Izmir'],['Black Sea Athletic','Trabzon'],['Central Anatolia FC','Konya'],['Mediterranean 1899','Antalya'],['Northgate SK','Samsun'],['Golden Horn City','Istanbul']];
const MANAGERS=['Marco Bellini','Daniel Hartmann','Carlos Mendez','Emre Kaya','Lucas Ferreira','Jonas Weber','Mateo Silva','Andreas Keller'];
function ensure(s){s.gameState.worldSim||={clubs:CLUBS.map((x,i)=>({id:i,name:x[0],city:x[1],manager:MANAGERS[i],rating:62+i*2,budget:2000000+i*350000,morale:60+i%4*7,lastAction:null})),history:[],seed:0,lastDate:s.gameState.date};}
function addNews(s,title,tag,detail){s.gameState.media||={news:[],events:[],press:[]};s.gameState.media.news.unshift({id:Date.now()+Math.random(),title,tag,detail,date:s.gameState.date,market:'GLOBAL'});s.gameState.media.news=s.gameState.media.news.slice(0,20)}
function tick(){const s=get();if(!s?.gameState?.club)return;ensure(s);if(s.gameState.worldSim.lastDate===s.gameState.date)return;const w=s.gameState.worldSim;w.seed++;w.lastDate=s.gameState.date;const c=w.clubs[(w.seed*7)%w.clubs.length];const roll=w.seed%10;if(roll<3){const old=c.manager;c.manager=MANAGERS[(w.seed+3)%MANAGERS.length];c.morale=Math.max(35,c.morale-5);addNews(s,`${c.name} teknik direktör değişikliğine gitti`,'WORLD',`${old} dönemi sona erdi. ${c.manager} yeni teknik direktör olarak göreve başladı.`)}else if(roll<6){const fee=Math.round((c.budget*.08+c.rating*12000)/50000)*50000;c.budget=Math.max(0,c.budget-fee);addNews(s,`${c.name} transfer piyasasında aktif`,'GLOBAL',`${c.name}, genç bir oyuncu için yaklaşık €${(fee/1000000).toFixed(1)}M yatırım yaptı.`)}else if(roll<8){c.morale=Math.min(100,c.morale+4);c.rating=Math.min(88,c.rating+1);addNews(s,`${c.name} yükselişte`,'LEAGUE',`${c.manager} yönetiminde takımın form grafiği dikkat çekiyor.`)}else{c.morale=Math.max(20,c.morale-8);addNews(s,`${c.name} finansal baskı altında`,'FINANCE',`${c.name} bütçesini korumak için kadro maliyetlerini gözden geçiriyor.`)}w.history.unshift({date:s.gameState.date,club:c.name,action:c.lastAction||'world event'});w.history=w.history.slice(0,30);save(s);render(s)}
function render(s=get()){if(!s?.gameState?.club)return;ensure(s);let host=document.getElementById('worldSimulation');if(!host){host=document.createElement('section');host.id='worldSimulation';host.className='world-sim';document.getElementById('dashboard')?.appendChild(host)}const w=s.gameState.worldSim;host.innerHTML=`<div class="media-card"><div class="media-head"><div><span class="eyebrow">GLOBAL FOOTBALL WORLD</span><h3>World Simulation</h3><p>Other clubs keep changing even when you are not watching.</p></div><span class="news-badge">${w.clubs.length} CLUBS</span></div><div class="world-clubs">${w.clubs.slice(0,8).map(c=>`<div class="world-club"><div><b>${c.name}</b><small>${c.city} · ${c.manager}</small></div><span>OVR ${c.rating}</span></div>`).join('')}</div></div>`}
window.NEXORA_WORLD={tick,render};let last='';setInterval(()=>{const s=get();if(s?.gameState?.date&&s.gameState.date!==last){last=s.gameState.date;setTimeout(tick,30)}},500);window.addEventListener('load',()=>setTimeout(render,200));window.addEventListener('nexora:career-ready',()=>setTimeout(()=>{const s=get();if(s){ensure(s);save(s);render(s)}},100));
})();