(()=>{
const K='nexoraCareer';const get=()=>{try{return JSON.parse(localStorage.getItem(K)||'null')}catch{return null}};const save=s=>localStorage.setItem(K,JSON.stringify(s));const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));
const CLUBS=[['Bosphorus United','Istanbul'],['Capital 1907','Ankara'],['Aegean Stars','Izmir'],['Black Sea Athletic','Trabzon'],['Central Anatolia FC','Konya'],['Mediterranean 1899','Antalya'],['Northgate SK','Samsun'],['Golden Horn City','Istanbul']];const MANAGERS=['Marco Bellini','Daniel Hartmann','Carlos Mendez','Emre Kaya','Lucas Ferreira','Jonas Weber','Mateo Silva','Andreas Keller','David Laurent','Milan Kovac'];
function ensure(s){if(!s.gameState.worldSim)s.gameState.worldSim={clubs:CLUBS.map((x,i)=>({id:i,name:x[0],city:x[1],manager:MANAGERS[i],rating:62+i*2,budget:2000000+i*350000,morale:60+(i%4)*7,form:50+(i%5)*8,pressure:25,lastAction:'Season preparation'})),history:[],seed:0,lastDate:null,otherResults:[]};s.gameState.worldSim.otherResults||=[];}
function news(s,title,tag,detail){s.gameState.media||={news:[],events:[],press:[]};s.gameState.media.news.unshift({id:Date.now()+Math.random(),title,tag,detail,date:s.gameState.date,market:'GLOBAL'});s.gameState.media.news=s.gameState.media.news.slice(0,24)}
function ensureStandings(s){const clubs=window.NEXORA_DATA?.clubs||[];s.gameState.standings||=clubs.map(c=>({clubId:c.id,name:c.name,code:c.code,played:0,wins:0,draws:0,losses:0,gf:0,ga:0,gd:0,points:0}));return s.gameState.standings}
function updateRow(t,gf,ga){t.played++;t.gf+=gf;t.ga+=ga;t.gd=t.gf-t.ga;if(gf>ga){t.wins++;t.points+=3}else if(gf===ga){t.draws++;t.points++}else t.losses++}
function simulateOtherResult(s){const table=ensureStandings(s),club=s.gameState.club;const pool=table.filter(x=>x.clubId!==club.id);if(pool.length<2)return null;const w=s.gameState.worldSim,seed=w.seed;const a=pool[seed%pool.length],b=pool[(seed*3+1)%pool.length];if(!a||!b||a===b)return null;const hg=(seed*7+a.played*3)%4,ag=(seed*11+b.played*2+1)%4;updateRow(a,hg,ag);updateRow(b,ag,hg);const r={date:s.gameState.date,home:a.name,away:b.name,homeGoals:hg,awayGoals:ag};w.otherResults.unshift(r);w.otherResults=w.otherResults.slice(0,12);news(s,`${a.name} ${hg}-${ag} ${b.name}`,'OTHER RESULTS','Dünyadaki simülasyon lig sonuçlarından biri puan durumuna işlendi.');window.dispatchEvent(new CustomEvent('nexora:standings-updated',{detail:{source:'WORLD_SIM',result:r}}));return r}
function simulateClub(s,c,w){const roll=(w.seed*13+c.id*7)%100;c.form=clamp(c.form+(roll>72?5:roll<22?-6:1),15,95);c.morale=clamp(c.morale+(c.form>70?3:c.form<35?-4:0));c.pressure=clamp(c.pressure+(c.morale<40?4:-1));if(roll<14){const old=c.manager;c.manager=MANAGERS[(w.seed+c.id*3)%MANAGERS.length];c.morale=clamp(c.morale-5);c.pressure=clamp(c.pressure+12);news(s,`${c.name} teknik direktör değişikliğine gitti`,'WORLD',`${old} dönemi sona erdi. ${c.manager} göreve başladı.`);return 'MANAGER CHANGE'}if(roll<31){const fee=Math.round((c.budget*(0.06+(roll%4)*.015)+c.rating*18000)/50000)*50000;c.budget=Math.max(0,c.budget-fee);c.rating=clamp(c.rating+1,45,90);news(s,`${c.name} transfer piyasasında aktif`,'GLOBAL',`${c.name}, kadrosunu güçlendirmek için yaklaşık €${(fee/1000000).toFixed(1)}M yatırım yaptı.`);return 'TRANSFER'}if(roll<48){c.form=clamp(c.form+9);c.morale=clamp(c.morale+7);return 'FORM RISE'}if(roll<64){c.morale=clamp(c.morale-8);c.pressure=clamp(c.pressure+7);return 'PRESSURE'}c.morale=clamp(c.morale+2);return 'STABLE'}
function tick(){const s=get();if(!s?.gameState?.club)return;ensure(s);const w=s.gameState.worldSim;if(w.lastDate===s.gameState.date)return;w.seed++;w.lastDate=s.gameState.date;const actions=[];w.clubs.forEach(c=>{if(c.id%2===w.seed%2||w.seed%3===0)actions.push({club:c.name,action:simulateClub(s,c,w)})});const other=simulateOtherResult(s);w.history.unshift({date:s.gameState.date,actions,otherResult:other});w.history=w.history.slice(0,30);save(s);render(s)}
function render(s=get()){if(!s?.gameState?.club)return;ensure(s);let host=document.getElementById('worldSimulation');if(!host){host=document.createElement('section');host.id='worldSimulation';host.className='world-sim';document.getElementById('dashboard')?.appendChild(host)}const w=s.gameState.worldSim,rows=w.clubs.map(c=>`<div class="world-club"><div><b>${c.name}</b><small>${c.city} · ${c.manager}</small></div><div class="world-bars"><span>OVR ${c.rating}</span><span>FORM ${Math.round(c.form)}</span><span>MOOD ${Math.round(c.morale)}</span></div></div>`).join(''),recent=w.otherResults.slice(0,5).map(r=>`<div class="world-event"><b>${r.date}</b><span>${r.home} ${r.homeGoals}-${r.awayGoals} ${r.away}</span></div>`).join('');host.innerHTML=`<div class="media-card"><div class="media-head"><div><span class="eyebrow">GLOBAL FOOTBALL WORLD</span><h3>Living Football World</h3><p>Sen oynarken diğer kulüpler kendi hikâyelerini yazıyor.</p></div><span class="news-badge">${w.clubs.length} CLUBS</span></div><div class="world-clubs">${rows}</div><div class="world-history"><strong>OTHER RESULTS · LIVE</strong>${recent||'<small>Henüz simüle edilmiş sonuç yok.</small>'}</div></div>`}
window.NEXORA_WORLD={tick,render};let last='';setInterval(()=>{const s=get();if(s?.gameState?.date&&s.gameState.date!==last){last=s.gameState.date;setTimeout(tick,30)}},500);window.addEventListener('load',()=>setTimeout(render,200));window.addEventListener('nexora:career-ready',()=>setTimeout(()=>{const s=get();if(s){ensure(s);save(s);render(s)}},100));window.addEventListener('nexora:day-advanced',()=>setTimeout(tick,60));
})();